{"Properties.T:Autodesk.Revit.UI.Selection.PickedBox":{"id":"Properties.T:Autodesk.Revit.UI.Selection.PickedBox","title":"PickedBox Properties","ns":"Autodesk.Revit.UI.Selection","members":{"props":[{"n":"Max","d":"Maximum coordinates (upper-right-front corner of the pick box)."},{"n":"Min","d":"Minimum coordinates (lower-left-rear corner of the pick box)."}]}},"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType)","title":"Selection.PickObject(ObjectType) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select one object.","sig":"public Reference PickObject(\n\tObjectType objectType\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.PickBox(Autodesk.Revit.UI.Selection.PickBoxStyle)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickBox(Autodesk.Revit.UI.Selection.PickBoxStyle)","title":"Selection.PickBox(PickBoxStyle) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Invokes a general purpose two-click editor that lets the user to specify a rectangular area on the screen.","sig":"public PickedBox PickBox(\n\tPickBoxStyle style\n)","remarks":"The method starts an editor and returns when it finishes. Returns a PickedBox that contains two XYZ points."},"N:Autodesk.Revit.UI.Selection":{"id":"N:Autodesk.Revit.UI.Selection","title":"Autodesk.Revit.UI.Selection Namespace","ns":"Autodesk.Revit.UI.Selection"},"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter,System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter,System.String)","title":"Selection.PickObjects(ObjectType, ISelectionFilter, String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple objects which pass a custom filter while showing a custom status prompt string.","sig":"public IList<Reference> PickObjects(\n\tObjectType objectType,\n\tISelectionFilter selectionFilter,\n\tstring statusPrompt\n)","remarks":"The user will be shown \"Finish\" and \"Cancel\" buttons on the dialog bar to complete the selection operation. Uncheck the \"Multiple\" check-box to select single object and it will return the selected object directly.Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle","title":"Selection.PickElementsByRectangle Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple elements by drawing a rectangle.","sig":"public IList<Element> PickElementsByRectangle()","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"T:Autodesk.Revit.UI.Selection.ObjectType":{"id":"T:Autodesk.Revit.UI.Selection.ObjectType","title":"ObjectType Enumeration","ns":"Autodesk.Revit.UI.Selection","desc":"This enumerated type contains object types allowed to be selected during selection operations.","sig":"public enum ObjectType"},"T:Autodesk.Revit.UI.Selection.Selection":{"id":"T:Autodesk.Revit.UI.Selection.Selection","title":"Selection Class","ns":"Autodesk.Revit.UI.Selection","desc":"Contains the current user selection of elements within the project.","sig":"public class Selection : IDisposable","remarks":"The Selection object is used to retrieve the current user selected elements when an external API command is executed.","inherit":["SystemObject","Autodesk.Revit.UI.SelectionSelection"],"members":{"props":[{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}],"methods":[{"n":"Dispose","d":"Releases all resources used by the Selection"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetElementIds","d":"Returns the ids of the elements that are currently selected within the project.\n   The selection may not be complete. See GetReferences for more options."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetReferences","d":"Returns the references that are currently selected."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"PickBox(PickBoxStyle)","d":"Invokes a general purpose two-click editor that lets the user to specify a rectangular area on the screen."},{"n":"PickBox(PickBoxStyle, String)","d":"Invokes a general purpose two-click editor that lets the user to specify a rectangular area on the screen."},{"n":"PickElementsByRectangle","d":"Prompts the user to select multiple elements by drawing a rectangle."},{"n":"PickElementsByRectangle(ISelectionFilter)","d":"Prompts the user to select multiple elements by drawing a rectangle which pass a customer filter."},{"n":"PickElementsByRectangle(String)","d":"Prompts the user to select multiple elements by drawing a rectangle while showing a custom status prompt string."},{"n":"PickElementsByRectangle(ISelectionFilter, String)","d":"Prompts the user to select multiple elements by drawing a rectangle which pass a customer filter while showing a custom status prompt string."},{"n":"PickObject(ObjectType)","d":"Prompts the user to select one object."},{"n":"PickObject(ObjectType, ISelectionFilter)","d":"Prompts the user to select one object which passes a custom filter."},{"n":"PickObject(ObjectType, String)","d":"Prompts the user to select one object while showing a custom status prompt string."},{"n":"PickObject(ObjectType, ISelectionFilter, String)","d":"Prompts the user to select one object which passes a custom filter while showing a custom status prompt string."},{"n":"PickObjects(ObjectType)","d":"Prompts the user to select multiple objects."},{"n":"PickObjects(ObjectType, ISelectionFilter)","d":"Prompts the user to select multiple objects which pass a customer filter."},{"n":"PickObjects(ObjectType, String)","d":"Prompts the user to select multiple objects while showing a custom status prompt string."},{"n":"PickObjects(ObjectType, ISelectionFilter, String)","d":"Prompts the user to select multiple objects which pass a custom filter while showing a custom status prompt string."},{"n":"PickObjects(ObjectType, ISelectionFilter, String, IListReference)","d":""},{"n":"PickPoint","d":"Prompts the user to pick a point on the active work plane."},{"n":"PickPoint(ObjectSnapTypes)","d":"Prompts the user to pick a point on the active work plane using specified snap settings."},{"n":"PickPoint(String)","d":"Prompts the user to pick a point on the active work plane while showing a custom status prompt string."},{"n":"PickPoint(ObjectSnapTypes, String)","d":"Prompts the user to pick a point on the active work plane using specified snap settings while showing a custom status prompt string."},{"n":"SetElementIds","d":""},{"n":"SetReferences","d":""},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.UI.Selection.SelectableInViewFilter.#ctor(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,System.Boolean)":{"id":"M:Autodesk.Revit.UI.Selection.SelectableInViewFilter.#ctor(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,System.Boolean)","title":"SelectableInViewFilter(Document, ElementId, Boolean) Constructor","ns":"Autodesk.Revit.UI.Selection","desc":"Constructs a new instance of an SelectableInViewFilter, with the option to pass all non-selectable elements.","sig":"public SelectableInViewFilter(\n\tDocument document,\n\tElementId viewId,\n\tbool inverted\n)"},"M:Autodesk.Revit.UI.Selection.ISelectionFilter.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)":{"id":"M:Autodesk.Revit.UI.Selection.ISelectionFilter.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)","title":"ISelectionFilter.AllowReference Method","ns":"Autodesk.Revit.UI.Selection","desc":"Override this post-filter method to specify if a reference to a piece of geometry is permitted to be selected.","sig":"bool AllowReference(\n\tReference reference,\n\tXYZ position\n)","remarks":"If an exception is thrown from this method, the element will not be permitted to be selected."},"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter)","title":"Selection.PickObjects(ObjectType, ISelectionFilter) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple objects which pass a customer filter.","sig":"public IList<Reference> PickObjects(\n\tObjectType objectType,\n\tISelectionFilter selectionFilter\n)","remarks":"The user will be shown \"Finish\" and \"Cancel\" buttons on the dialog bar to complete the selection operation. Uncheck the \"Multiple\" check-box to select single object and it will return the selected object directly.Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.PickBox(Autodesk.Revit.UI.Selection.PickBoxStyle,System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickBox(Autodesk.Revit.UI.Selection.PickBoxStyle,System.String)","title":"Selection.PickBox(PickBoxStyle, String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Invokes a general purpose two-click editor that lets the user to specify a rectangular area on the screen.","sig":"public PickedBox PickBox(\n\tPickBoxStyle style,\n\tstring statusPrompt\n)","remarks":"The method starts an editor and returns when it finishes. Returns a PickedBox that contains two XYZ points."},"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType,System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType,System.String)","title":"Selection.PickObject(ObjectType, String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select one object while showing a custom status prompt string.","sig":"public Reference PickObject(\n\tObjectType objectType,\n\tstring statusPrompt\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.GetElementIds":{"id":"M:Autodesk.Revit.UI.Selection.Selection.GetElementIds","title":"Selection.GetElementIds Method","ns":"Autodesk.Revit.UI.Selection","desc":"Returns the ids of the elements that are currently selected within the project.\n   The selection may not be complete. See GetReferences for more options.","sig":"public ICollection<ElementId> GetElementIds()"},"M:Autodesk.Revit.UI.Selection.Selection.Dispose":{"id":"M:Autodesk.Revit.UI.Selection.Selection.Dispose","title":"Selection.Dispose Method","ns":"Autodesk.Revit.UI.Selection","desc":"Releases all resources used by the Selection","sig":"public void Dispose()"},"M:Autodesk.Revit.UI.Selection.Selection.GetReferences":{"id":"M:Autodesk.Revit.UI.Selection.Selection.GetReferences","title":"Selection.GetReferences Method","ns":"Autodesk.Revit.UI.Selection","desc":"Returns the references that are currently selected.","sig":"public IList<Reference> GetReferences()","remarks":"The references can be an element or subelement in the host or a linked document."},"T:Autodesk.Revit.UI.Selection.SelectableInViewFilter":{"id":"T:Autodesk.Revit.UI.Selection.SelectableInViewFilter","title":"SelectableInViewFilter Class","ns":"Autodesk.Revit.UI.Selection","desc":"A filter that passes elements that are selectable in the given view.","sig":"public class SelectableInViewFilter : ElementSlowFilter","remarks":"This filter is a slow filter. Slow filters require that the Element be obtained and expanded in memory first. Thus it is preferable to couple this filter with at least one ElementQuickFilter, which should minimize the number of Elements that are expanded. This filter is designed to operate on a list of elements visible in the given view. This can be obtained from a FilteredElementCollector constructed with the view id. This filter may not correctly restrict elements which are not a part of the visible elements of the view.","inherit":["SystemObject","Autodesk.Revit.DBElementFilter","Autodesk.Revit.DBElementSlowFilter","Autodesk.Revit.UI.SelectionSelectableInViewFilter"],"members":{"props":[{"n":"Inverted","d":"True if the results of the filter are inverted; elements that would normally be accepted by this filter will be rejected,\n   and elements that would normally be rejected will be accepted.\n(Inherited from ElementFilter)"},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity.\n(Inherited from ElementFilter)"}],"methods":[{"n":"Dispose","d":"(Inherited from ElementFilter)"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"PassesFilter(Element)","d":"Applies the filter to a given element.\n(Inherited from ElementFilter)"},{"n":"PassesFilter(Document, ElementId)","d":"Applies the filter to a given element.\n(Inherited from ElementFilter)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle(Autodesk.Revit.UI.Selection.ISelectionFilter,System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle(Autodesk.Revit.UI.Selection.ISelectionFilter,System.String)","title":"Selection.PickElementsByRectangle(ISelectionFilter, String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple elements by drawing a rectangle which pass a customer filter while showing a custom status prompt string.","sig":"public IList<Element> PickElementsByRectangle(\n\tISelectionFilter selectionFilter,\n\tstring statusPrompt\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType)","title":"Selection.PickObjects(ObjectType) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple objects.","sig":"public IList<Reference> PickObjects(\n\tObjectType objectType\n)","remarks":"The user will be shown \"Finish\" and \"Cancel\" buttons on the dialog bar to complete the selection operation. Uncheck the \"Multiple\" check-box to select single object and it will return the selected object directly.Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"Properties.T:Autodesk.Revit.UI.Selection.SelectableInViewFilter":{"id":"Properties.T:Autodesk.Revit.UI.Selection.SelectableInViewFilter","title":"SelectableInViewFilter Properties","ns":"Autodesk.Revit.UI.Selection","members":{"props":[{"n":"Inverted","d":"True if the results of the filter are inverted; elements that would normally be accepted by this filter will be rejected,\n   and elements that would normally be rejected will be accepted.\n(Inherited from ElementFilter)"},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity.\n(Inherited from ElementFilter)"}]}},"P:Autodesk.Revit.UI.Selection.PickedBox.Max":{"id":"P:Autodesk.Revit.UI.Selection.PickedBox.Max","title":"PickedBox.Max Property","ns":"Autodesk.Revit.UI.Selection","desc":"Maximum coordinates (upper-right-front corner of the pick box).","sig":"public XYZ Max { get; set; }"},"M:Autodesk.Revit.UI.Selection.Selection.PickPoint(Autodesk.Revit.UI.Selection.ObjectSnapTypes)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickPoint(Autodesk.Revit.UI.Selection.ObjectSnapTypes)","title":"Selection.PickPoint(ObjectSnapTypes) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to pick a point on the active work plane using specified snap settings.","sig":"public XYZ PickPoint(\n\tObjectSnapTypes snapSettings\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown. Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"Properties.T:Autodesk.Revit.UI.Selection.Selection":{"id":"Properties.T:Autodesk.Revit.UI.Selection.Selection","title":"Selection Properties","ns":"Autodesk.Revit.UI.Selection","members":{"props":[{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}]}},"Overload:Autodesk.Revit.UI.Selection.SelectableInViewFilter.#ctor":{"id":"Overload:Autodesk.Revit.UI.Selection.SelectableInViewFilter.#ctor","title":"SelectableInViewFilter Constructor","ns":"Autodesk.Revit.UI.Selection"},"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter)","title":"Selection.PickObject(ObjectType, ISelectionFilter) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select one object which passes a custom filter.","sig":"public Reference PickObject(\n\tObjectType objectType,\n\tISelectionFilter selectionFilter\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"T:Autodesk.Revit.UI.Selection.ObjectSnapTypes":{"id":"T:Autodesk.Revit.UI.Selection.ObjectSnapTypes","title":"ObjectSnapTypes Enumeration","ns":"Autodesk.Revit.UI.Selection","desc":"This enumerated type contains object snap types allowed to be set during PickPoint operations.","sig":"[FlagsAttribute]\npublic enum ObjectSnapTypes"},"M:Autodesk.Revit.UI.Selection.Selection.PickPoint(System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickPoint(System.String)","title":"Selection.PickPoint(String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to pick a point on the active work plane while showing a custom status prompt string.","sig":"public XYZ PickPoint(\n\tstring statusPrompt\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown. Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.SetReferences(System.Collections.Generic.IList{Autodesk.Revit.DB.Reference})":{"id":"M:Autodesk.Revit.UI.Selection.Selection.SetReferences(System.Collections.Generic.IList{Autodesk.Revit.DB.Reference})","title":"Selection.SetReferences Method","ns":"Autodesk.Revit.UI.Selection","sig":"public void SetReferences(\n\tIList<Reference> references\n)"},"Methods.T:Autodesk.Revit.UI.Selection.ISelectionFilter":{"id":"Methods.T:Autodesk.Revit.UI.Selection.ISelectionFilter","title":"ISelectionFilter Methods","ns":"Autodesk.Revit.UI.Selection","members":{"methods":[{"n":"AllowElement","d":"Override this pre-filter method to specify if the element should be permitted to be selected."},{"n":"AllowReference","d":"Override this post-filter method to specify if a reference to a piece of geometry is permitted to be selected."}]}},"Overload:Autodesk.Revit.UI.Selection.Selection.PickBox":{"id":"Overload:Autodesk.Revit.UI.Selection.Selection.PickBox","title":"Selection.PickBox Method","ns":"Autodesk.Revit.UI.Selection"},"P:Autodesk.Revit.UI.Selection.PickedBox.Min":{"id":"P:Autodesk.Revit.UI.Selection.PickedBox.Min","title":"PickedBox.Min Property","ns":"Autodesk.Revit.UI.Selection","desc":"Minimum coordinates (lower-left-rear corner of the pick box).","sig":"public XYZ Min { get; set; }"},"M:Autodesk.Revit.UI.Selection.ISelectionFilter.AllowElement(Autodesk.Revit.DB.Element)":{"id":"M:Autodesk.Revit.UI.Selection.ISelectionFilter.AllowElement(Autodesk.Revit.DB.Element)","title":"ISelectionFilter.AllowElement Method","ns":"Autodesk.Revit.UI.Selection","desc":"Override this pre-filter method to specify if the element should be permitted to be selected.","sig":"bool AllowElement(\n\tElement elem\n)","remarks":"If prompting the user to select an element from a Revit Link instance, the element passed here will be the link instance, not the selected linked element. Access the linked element from Reference passed to the AllowReference() callback of ISelectionFilter.If an exception is thrown from this method, the element will not be permitted to be selected."},"Methods.T:Autodesk.Revit.UI.Selection.SelectableInViewFilter":{"id":"Methods.T:Autodesk.Revit.UI.Selection.SelectableInViewFilter","title":"SelectableInViewFilter Methods","ns":"Autodesk.Revit.UI.Selection","members":{"methods":[{"n":"Dispose","d":"(Inherited from ElementFilter)"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"PassesFilter(Element)","d":"Applies the filter to a given element.\n(Inherited from ElementFilter)"},{"n":"PassesFilter(Document, ElementId)","d":"Applies the filter to a given element.\n(Inherited from ElementFilter)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"Overload:Autodesk.Revit.UI.Selection.Selection.PickPoint":{"id":"Overload:Autodesk.Revit.UI.Selection.Selection.PickPoint","title":"Selection.PickPoint Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to pick a point on the active work plane."},"Methods.T:Autodesk.Revit.UI.Selection.Selection":{"id":"Methods.T:Autodesk.Revit.UI.Selection.Selection","title":"Selection Methods","ns":"Autodesk.Revit.UI.Selection","members":{"methods":[{"n":"Dispose","d":""},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetElementIds","d":"Returns the ids of the elements that are currently selected within the project.\n   The selection may not be complete. See GetReferences for more options."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetReferences","d":"Returns the references that are currently selected."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"PickBox(PickBoxStyle)","d":"Invokes a general purpose two-click editor that lets the user to specify a rectangular area on the screen."},{"n":"PickBox(PickBoxStyle, String)","d":"Invokes a general purpose two-click editor that lets the user to specify a rectangular area on the screen."},{"n":"PickElementsByRectangle","d":"Prompts the user to select multiple elements by drawing a rectangle."},{"n":"PickElementsByRectangle(ISelectionFilter)","d":"Prompts the user to select multiple elements by drawing a rectangle which pass a customer filter."},{"n":"PickElementsByRectangle(String)","d":"Prompts the user to select multiple elements by drawing a rectangle while showing a custom status prompt string."},{"n":"PickElementsByRectangle(ISelectionFilter, String)","d":"Prompts the user to select multiple elements by drawing a rectangle which pass a customer filter while showing a custom status prompt string."},{"n":"PickObject(ObjectType)","d":"Prompts the user to select one object."},{"n":"PickObject(ObjectType, ISelectionFilter)","d":"Prompts the user to select one object which passes a custom filter."},{"n":"PickObject(ObjectType, String)","d":"Prompts the user to select one object while showing a custom status prompt string."},{"n":"PickObject(ObjectType, ISelectionFilter, String)","d":"Prompts the user to select one object which passes a custom filter while showing a custom status prompt string."},{"n":"PickObjects(ObjectType)","d":"Prompts the user to select multiple objects."},{"n":"PickObjects(ObjectType, ISelectionFilter)","d":"Prompts the user to select multiple objects which pass a customer filter."},{"n":"PickObjects(ObjectType, String)","d":"Prompts the user to select multiple objects while showing a custom status prompt string."},{"n":"PickObjects(ObjectType, ISelectionFilter, String)","d":"Prompts the user to select multiple objects which pass a custom filter while showing a custom status prompt string."},{"n":"PickObjects(ObjectType, ISelectionFilter, String, IListReference)","d":""},{"n":"PickPoint","d":"Prompts the user to pick a point on the active work plane."},{"n":"PickPoint(ObjectSnapTypes)","d":"Prompts the user to pick a point on the active work plane using specified snap settings."},{"n":"PickPoint(String)","d":"Prompts the user to pick a point on the active work plane while showing a custom status prompt string."},{"n":"PickPoint(ObjectSnapTypes, String)","d":"Prompts the user to pick a point on the active work plane using specified snap settings while showing a custom status prompt string."},{"n":"SetElementIds","d":""},{"n":"SetReferences","d":""},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"T:Autodesk.Revit.UI.Selection.PickedBox":{"id":"T:Autodesk.Revit.UI.Selection.PickedBox","title":"PickedBox Class","ns":"Autodesk.Revit.UI.Selection","desc":"A class that contains two XYZ points representing the pick box on the screen.","sig":"public class PickedBox","inherit":["SystemObject","Autodesk.Revit.UI.SelectionPickedBox"],"members":{"props":[{"n":"Max","d":"Maximum coordinates (upper-right-front corner of the pick box)."},{"n":"Min","d":"Minimum coordinates (lower-left-rear corner of the pick box)."}],"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.UI.Selection.Selection.PickPoint(Autodesk.Revit.UI.Selection.ObjectSnapTypes,System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickPoint(Autodesk.Revit.UI.Selection.ObjectSnapTypes,System.String)","title":"Selection.PickPoint(ObjectSnapTypes, String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to pick a point on the active work plane using specified snap settings while showing a custom status prompt string.","sig":"public XYZ PickPoint(\n\tObjectSnapTypes snapSettings,\n\tstring statusPrompt\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown. Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"Overload:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle":{"id":"Overload:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle","title":"Selection.PickElementsByRectangle Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple elements by drawing a rectangle."},"T:Autodesk.Revit.UI.Selection.PickBoxStyle":{"id":"T:Autodesk.Revit.UI.Selection.PickBoxStyle","title":"PickBoxStyle Enumeration","ns":"Autodesk.Revit.UI.Selection","desc":"The enum that controls the style of the pick box.","sig":"public enum PickBoxStyle"},"M:Autodesk.Revit.UI.Selection.SelectableInViewFilter.#ctor(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId)":{"id":"M:Autodesk.Revit.UI.Selection.SelectableInViewFilter.#ctor(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId)","title":"SelectableInViewFilter(Document, ElementId) Constructor","ns":"Autodesk.Revit.UI.Selection","desc":"Constructs a new instance of an SelectableInViewFilter.","sig":"public SelectableInViewFilter(\n\tDocument document,\n\tElementId viewId\n)"},"Methods.T:Autodesk.Revit.UI.Selection.PickedBox":{"id":"Methods.T:Autodesk.Revit.UI.Selection.PickedBox","title":"PickedBox Methods","ns":"Autodesk.Revit.UI.Selection","members":{"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle(Autodesk.Revit.UI.Selection.ISelectionFilter)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle(Autodesk.Revit.UI.Selection.ISelectionFilter)","title":"Selection.PickElementsByRectangle(ISelectionFilter) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple elements by drawing a rectangle which pass a customer filter.","sig":"public IList<Element> PickElementsByRectangle(\n\tISelectionFilter selectionFilter\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"P:Autodesk.Revit.UI.Selection.Selection.IsValidObject":{"id":"P:Autodesk.Revit.UI.Selection.Selection.IsValidObject","title":"Selection.IsValidObject Property","ns":"Autodesk.Revit.UI.Selection","desc":"Specifies whether the .NET object represents a valid Revit entity.","sig":"public bool IsValidObject { get; }","remarks":"If the corresponding Revit native object is destroyed, or creation of the corresponding object is undone, a managed API object containing it is no longer valid. API methods cannot be called on invalidated wrapper objects."},"Overload:Autodesk.Revit.UI.Selection.Selection.PickObject":{"id":"Overload:Autodesk.Revit.UI.Selection.Selection.PickObject","title":"Selection.PickObject Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select one object."},"M:Autodesk.Revit.UI.Selection.Selection.SetElementIds(System.Collections.Generic.ICollection{Autodesk.Revit.DB.ElementId})":{"id":"M:Autodesk.Revit.UI.Selection.Selection.SetElementIds(System.Collections.Generic.ICollection{Autodesk.Revit.DB.ElementId})","title":"Selection.SetElementIds Method","ns":"Autodesk.Revit.UI.Selection","sig":"public void SetElementIds(\n\tICollection<ElementId> elementIds\n)"},"T:Autodesk.Revit.UI.Selection.ISelectionFilter":{"id":"T:Autodesk.Revit.UI.Selection.ISelectionFilter","title":"ISelectionFilter Interface","ns":"Autodesk.Revit.UI.Selection","desc":"An interface that provides the ability to filter objects during a selection operation.","sig":"public interface ISelectionFilter","members":{"methods":[{"n":"AllowElement","d":"Override this pre-filter method to specify if the element should be permitted to be selected."},{"n":"AllowReference","d":"Override this post-filter method to specify if a reference to a piece of geometry is permitted to be selected."}]}},"M:Autodesk.Revit.UI.Selection.Selection.PickPoint":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickPoint","title":"Selection.PickPoint Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to pick a point on the active work plane.","sig":"public XYZ PickPoint()","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown. Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter,System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObject(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter,System.String)","title":"Selection.PickObject(ObjectType, ISelectionFilter, String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select one object which passes a custom filter while showing a custom status prompt string.","sig":"public Reference PickObject(\n\tObjectType objectType,\n\tISelectionFilter selectionFilter,\n\tstring statusPrompt\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"Overload:Autodesk.Revit.UI.Selection.Selection.PickObjects":{"id":"Overload:Autodesk.Revit.UI.Selection.Selection.PickObjects","title":"Selection.PickObjects Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple objects."},"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter,System.String,System.Collections.Generic.IList{Autodesk.Revit.DB.Reference})":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,Autodesk.Revit.UI.Selection.ISelectionFilter,System.String,System.Collections.Generic.IList{Autodesk.Revit.DB.Reference})","title":"Selection.PickObjects(ObjectType, ISelectionFilter, String, IList<Reference>) Method","ns":"Autodesk.Revit.UI.Selection","sig":"public IList<Reference> PickObjects(\n\tObjectType objectType,\n\tISelectionFilter selectionFilter,\n\tstring statusPrompt,\n\tIList<Reference> pPreSelected\n)"},"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickObjects(Autodesk.Revit.UI.Selection.ObjectType,System.String)","title":"Selection.PickObjects(ObjectType, String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple objects while showing a custom status prompt string.","sig":"public IList<Reference> PickObjects(\n\tObjectType objectType,\n\tstring statusPrompt\n)","remarks":">The user will be shown \"Finish\" and \"Cancel\" buttons on the dialog bar to complete the selection operation. Uncheck the \"Multiple\" check-box to select single object and it will return the selected object directly.Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."},"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle(System.String)":{"id":"M:Autodesk.Revit.UI.Selection.Selection.PickElementsByRectangle(System.String)","title":"Selection.PickElementsByRectangle(String) Method","ns":"Autodesk.Revit.UI.Selection","desc":"Prompts the user to select multiple elements by drawing a rectangle while showing a custom status prompt string.","sig":"public IList<Element> PickElementsByRectangle(\n\tstring statusPrompt\n)","remarks":"Revit users will be permitted to manipulate the Revit view (zooming, panning, and rotating the view), but will not be permitted to click other items in the Revit user interface. Users are not permitted to switch the active view, close the active document or Revit application in the pick session, otherwise an exception will be thrown.The selection will not be automatically added to the active selection buffer.Note: this method must not be called during dynamic update, otherwise ForbiddenForDynamicUpdateException will be thrown."}}