{"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetClosestStation(Autodesk.Revit.DB.XYZ)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetClosestStation(Autodesk.Revit.DB.XYZ)","title":"Alignment.GetClosestStation Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculates the alignment station closest to the given model point.","sig":"public double GetClosestStation(\n\tXYZ point\n)"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.Get(Autodesk.Revit.DB.Element)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.Get(Autodesk.Revit.DB.Element)","title":"Alignment.Get(Element) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns an Alignment object given a Revit alignment element.","sig":"public static Alignment Get(\n\tElement alignmentElement\n)"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.AlignmentId":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.AlignmentId","title":"AlignmentStationLabel.AlignmentId Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The ElementId of the Alignment on which the SpotDimension is placed.","sig":"public ElementId AlignmentId { get; }"},"P:Autodesk.Revit.DB.Infrastructure.Alignment.DisplayedStartStation":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.DisplayedStartStation","title":"Alignment.DisplayedStartStation Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the station at which the alignment's display starts, in Revit internal model units (standard Imperial feet).","sig":"public double DisplayedStartStation { get; }","remarks":"This station is within the alignment's geometric definition range (StartStation, EndStation)."},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetClosestPoint(Autodesk.Revit.DB.XYZ)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetClosestPoint(Autodesk.Revit.DB.XYZ)","title":"Alignment.GetClosestPoint Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculates the point on the alignment's geometry which is closest to the given model point.","sig":"public XYZ GetClosestPoint(\n\tXYZ point\n)"},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.GetAlignmentStationLabels(Autodesk.Revit.DB.Infrastructure.Alignment)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.GetAlignmentStationLabels(Autodesk.Revit.DB.Infrastructure.Alignment)","title":"AlignmentStationLabel.GetAlignmentStationLabels(Alignment) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns all alignment station labels placed on the given alignment.","sig":"public static ICollection<AlignmentStationLabel> GetAlignmentStationLabels(\n\tAlignment alignment\n)","remarks":"The resulting collection may contain both \"individual\" labels (created via Create(Alignment, View, AlignmentStationLabelOptions)) and \"labels in set\" (created via CreateSet(Alignment, View, AlignmentStationLabelSetOptions)). These labels have categories respectively OST_Alignments and OST_AlignmentStationLabelSets."},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValid(Autodesk.Revit.DB.Element)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValid(Autodesk.Revit.DB.Element)","title":"AlignmentStationLabel.IsValid(Element) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Checks if the element is a valid alignment station label.","sig":"public static bool IsValid(\n\tElement element\n)"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Station":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Station","title":"AlignmentStationLabel.Station Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The alignment station at which the SpotDimension is placed.","sig":"public double Station { get; set; }"},"T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions":{"id":"T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions","title":"AlignmentStationLabelSetOptions Class","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Represents an object containing options for creating a set of AlignmentStationLabel.","sig":"public class AlignmentStationLabelSetOptions","inherit":["SystemObject","Autodesk.Revit.DB.InfrastructureAlignmentStationLabelSetOptions"],"members":{"props":[{"n":"EndStation","d":"The ending station for creating labels in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, the station value corresponding to the alignment's DisplayedEndStation is used."},{"n":"HasLeader","d":"Specifies if the label will have a leader. \n               The default value is true."},{"n":"Interval","d":"The interval between labels to be created in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, a predefined interval value will be used, depending on the unit setting for stationing units in the document.\n               For standard imperial, the default is 100 ft.\n               For survey imperial, the default is 100 USft (US survey).\n               For metric, the default is 1000 m."},{"n":"Offset","d":"The offset of the labels from the alignment, in Revit internal paper space units (standard Imperial feet).\n               A positive offset creates labels to the right of the alignment, a negative - to the left.\n               The default value is null.\n               If null, a predefined offset value will be used, depending on the unit setting for stationing units in the document.\n               For standard imperial, the default is 1/8\".\n               For survey imperial, the default is 1/8\" (US survey).\n               For metric, the default is 5 mm."},{"n":"StartStation","d":"The starting station for creating labels in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, the station value corresponding to the alignment's DisplayedStartStation is used."},{"n":"TypeId","d":"Specifies the ElementId of the labels' type.\n               The default value is InvalidElementId. in this case, CreateSet(Alignment, View, AlignmentStationLabelSetOptions) will throw an exception."}],"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"Properties.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions":{"id":"Properties.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions","title":"AlignmentStationLabelSetOptions Properties","ns":"Autodesk.Revit.DB.Infrastructure","members":{"props":[{"n":"EndStation","d":"The ending station for creating labels in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, the station value corresponding to the alignment's DisplayedEndStation is used."},{"n":"HasLeader","d":"Specifies if the label will have a leader. \n               The default value is true."},{"n":"Interval","d":"The interval between labels to be created in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, a predefined interval value will be used, depending on the unit setting for stationing units in the document.\n               For standard imperial, the default is 100 ft.\n               For survey imperial, the default is 100 USft (US survey).\n               For metric, the default is 1000 m."},{"n":"Offset","d":"The offset of the labels from the alignment, in Revit internal paper space units (standard Imperial feet).\n               A positive offset creates labels to the right of the alignment, a negative - to the left.\n               The default value is null.\n               If null, a predefined offset value will be used, depending on the unit setting for stationing units in the document.\n               For standard imperial, the default is 1/8\".\n               For survey imperial, the default is 1/8\" (US survey).\n               For metric, the default is 5 mm."},{"n":"StartStation","d":"The starting station for creating labels in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, the station value corresponding to the alignment's DisplayedStartStation is used."},{"n":"TypeId","d":"Specifies the ElementId of the labels' type.\n               The default value is InvalidElementId. in this case, CreateSet(Alignment, View, AlignmentStationLabelSetOptions) will throw an exception."}]}},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetDistance(System.Double,System.Double)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetDistance(System.Double,System.Double)","title":"Alignment.GetDistance Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculates the relative distance along the alignment between two stations based on their alignment distances\n               according to Revit Internal Origin Coordinate Base. The distance may be positive or negative depending on\n               the relative positions of the input stations on the alignment.","sig":"public double GetDistance(\n\tdouble fromStation,\n\tdouble toStation\n)"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetPointAtStation(System.Double)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetPointAtStation(System.Double)","title":"Alignment.GetPointAtStation Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculates the model point for a given alignment station.","sig":"public XYZ GetPointAtStation(\n\tdouble station\n)"},"Methods.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions":{"id":"Methods.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions","title":"AlignmentStationLabelSetOptions Methods","ns":"Autodesk.Revit.DB.Infrastructure","members":{"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.Station":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.Station","title":"AlignmentStationLabelOptions.Station Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the station at which the label will be placed, in Revit internal model units (standard Imperial feet).\n               The station determines the location of the label's origin: Origin \n               by setting it to the closest point on the alignment geometry which corresponds to this station.","sig":"public double Station { get; set; }"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Element":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Element","title":"AlignmentStationLabel.Element Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The underlying SpotDimension element.","sig":"public Element Element { get; }"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.HasLeader":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.HasLeader","title":"AlignmentStationLabelOptions.HasLeader Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies if the label will have a leader. \n               The default value is true.","sig":"public bool HasLeader { get; set; }"},"Overload:Autodesk.Revit.DB.Infrastructure.Alignment.Get":{"id":"Overload:Autodesk.Revit.DB.Infrastructure.Alignment.Get","title":"Alignment.Get Method","ns":"Autodesk.Revit.DB.Infrastructure"},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.CreateRecommendedTypeForSet(Autodesk.Revit.DB.Document)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.CreateRecommendedTypeForSet(Autodesk.Revit.DB.Document)","title":"AlignmentStationLabel.CreateRecommendedTypeForSet Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Creates an element type recommended for alignment label sets and returns its ElementId.","sig":"public static ElementId CreateRecommendedTypeForSet(\n\tDocument document\n)","remarks":"The crucial features of the label type recommended for sets are: - rotate with component - vertical text - label display includes station value - leader arrow head has type \"Heavy End Tick Mark\""},"Overload:Autodesk.Revit.DB.Infrastructure.Alignment.GetAlignments":{"id":"Overload:Autodesk.Revit.DB.Infrastructure.Alignment.GetAlignments","title":"Alignment.GetAlignments Method","ns":"Autodesk.Revit.DB.Infrastructure"},"P:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint.PreviousCurveType":{"id":"P:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint.PreviousCurveType","title":"HorizontalCurveEndpoint.PreviousCurveType Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The HorizontalCurveType \n               of the curve which connects the endpoint to the previous displayed curve.\n               If this endpoint's Station equals \n               DisplayedStartStation, returns Unknown curve type.","sig":"public HorizontalCurveType PreviousCurveType { get; }"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.TypeId":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.TypeId","title":"AlignmentStationLabelSetOptions.TypeId Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the ElementId of the labels' type.\n               The default value is InvalidElementId. in this case, CreateSet(Alignment, View, AlignmentStationLabelSetOptions) will throw an exception.","sig":"public ElementId TypeId { get; set; }","remarks":"Recommended types can be found using IsRecommendedTypeForSet(Element) Other valid types can be found using IsValidType(Element)."},"P:Autodesk.Revit.DB.Infrastructure.Alignment.Element":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.Element","title":"Alignment.Element Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The underlying DirectShape element.","sig":"public Element Element { get; }"},"T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel":{"id":"T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel","title":"AlignmentStationLabel Class","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Represents an object which provides access to a specialized Revit annotation element \n               used for labeling Alignment stations.","sig":"public class AlignmentStationLabel","remarks":"The element is a SpotDimension. The element's category is OST_AlignmentStationLabels or, if in a set of labels, OST_AlignmentStationLabelSets. The element's type is a SpotDimensionType with DimensionStyleType equal to AlignmentStationLabel. The element's Origin is a point on the tessellated representation of an alignment. To get the precise point on the alignment's curve, use GetPointAtStation(Double) with input obtained from Station.","inherit":["SystemObject","Autodesk.Revit.DB.InfrastructureAlignmentStationLabel"],"members":{"props":[{"n":"AlignmentId","d":"The ElementId of the Alignment on which the SpotDimension is placed."},{"n":"Element","d":"The underlying SpotDimension element."},{"n":"Station","d":"The alignment station at which the SpotDimension is placed."}],"methods":[{"n":"Create","d":"Creates an AlignmentStationLabel object along with its underlying SpotDimension element. \n               Returns null if element creation fails."},{"n":"CreateRecommendedTypeForSet","d":"Creates an element type recommended for alignment label sets and returns its ElementId."},{"n":"CreateSet","d":"Creates a collection of AlignmentStationLabel objects along with their underlying SpotDimension elements."},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"Get","d":"Returns an AlignmentStationLabel object for the given element."},{"n":"GetAlignmentStationLabels(Alignment)","d":"Returns all alignment station labels placed on the given alignment."},{"n":"GetAlignmentStationLabels(Alignment, ElementId)","d":"Returns all alignment station labels placed on the given alignment in the given view."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsRecommendedTypeForSet","d":"Checks if the element type is recommended for alignment labels in sets."},{"n":"IsValid","d":"Checks if this object is a valid alignment station label."},{"n":"IsValid(Element)","d":"Checks if the element is a valid alignment station label."},{"n":"IsValidType","d":"Checks if the type is a valid alignment station label type."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.StartStation":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.StartStation","title":"AlignmentStationLabelSetOptions.StartStation Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The starting station for creating labels in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, the station value corresponding to the alignment's DisplayedStartStation is used.","sig":"public double? StartStation { get; set; }"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.HasLeader":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.HasLeader","title":"AlignmentStationLabelSetOptions.HasLeader Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies if the label will have a leader. \n               The default value is true.","sig":"public bool HasLeader { get; set; }"},"T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions":{"id":"T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions","title":"AlignmentStationLabelOptions Class","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Represents an object containing options for creating an AlignmentStationLabel.","sig":"public class AlignmentStationLabelOptions","inherit":["SystemObject","Autodesk.Revit.DB.InfrastructureAlignmentStationLabelOptions"],"members":{"props":[{"n":"HasLeader","d":"Specifies if the label will have a leader. \n               The default value is true."},{"n":"LeaderEnd","d":"Specifies the leader end point, in model coordinates. \n               The default value is null.\n               When null, the end point will be the same as the Origin point, \n               driven by the Station value."},{"n":"LeaderShoulder","d":"Specifies the leader shoulder point, in model coordinates. \n               The default value is null.\n               When null, the shoulder point will be the same as the Origin point, \n               driven by the Station value."},{"n":"Station","d":"Specifies the station at which the label will be placed, in Revit internal model units (standard Imperial feet).\n               The station determines the location of the label's origin: Origin \n               by setting it to the closest point on the alignment geometry which corresponds to this station."},{"n":"TypeId","d":"Specifies the ElementId of the label type. \n               The default value is InvalidElementId. In this case, the default type id for alignment station labels in the document is used."}],"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"T:Autodesk.Revit.DB.Infrastructure.Alignment":{"id":"T:Autodesk.Revit.DB.Infrastructure.Alignment","title":"Alignment Class","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Represents an object which provides access to an underlying Revit alignment element.","sig":"public class Alignment","remarks":"The element is a DirectShape. The element's category is OST_Alignments.","inherit":["SystemObject","Autodesk.Revit.DB.InfrastructureAlignment"],"members":{"props":[{"n":"Description","d":"The Description of this alignment."},{"n":"DisplayedEndStation","d":"Specifies the station at which the alignment's display ends, in Revit internal model units (standard Imperial feet)."},{"n":"DisplayedStartStation","d":"Specifies the station at which the alignment's display starts, in Revit internal model units (standard Imperial feet)."},{"n":"Element","d":"The underlying DirectShape element."},{"n":"EndStation","d":"Specifies the station at which the alignment's geometric definition ends, in Revit internal model units (standard Imperial feet)."},{"n":"GUID","d":"The GUID of this alignment."},{"n":"Name","d":"The Name of this alignment."},{"n":"StartStation","d":"Specifies the station at which the alignment's geometric definition starts, in Revit internal model units (standard Imperial feet)."}],"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"Get(Element)","d":"Returns an Alignment object given a Revit alignment element."},{"n":"Get(Document, Guid)","d":"Returns an Alignment in the document given its GUID."},{"n":"GetAlignments(Document)","d":"Returns all alignments in the given document."},{"n":"GetAlignments(View)","d":"Returns all alignments visible in the given view."},{"n":"GetClosestPoint","d":"Calculates the point on the alignment's geometry which is closest to the given model point."},{"n":"GetClosestStation","d":"Calculates the alignment station closest to the given model point."},{"n":"GetDisplayedHorizontalCurveEndpoints","d":"Returns the endpoints of the alignment's horizontal curves.\n               Only the points between DisplayedStartStation \n               and DisplayedEndStation are returned."},{"n":"GetDistance","d":"Calculates the relative distance along the alignment between two stations based on their alignment distances\n               according to Revit Internal Origin Coordinate Base. The distance may be positive or negative depending on\n               the relative positions of the input stations on the alignment."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetHCurveNormalAtStation","d":"Calculate 2d (X and Y components of returned vector) horizontal normal at given station."},{"n":"GetHCurveTangentAtStation","d":"Calculate 2d (X and Y components of returned vector) horizontal tangent at given station."},{"n":"GetPointAtStation","d":"Calculates the model point for a given alignment station."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"GetVCurveNormalAtStation","d":"Calculate 2d (X and Y components of returned vector) vertical normal at given station."},{"n":"GetVCurveTangentAtStation","d":"Calculate 2d (X and Y components of returned vector) vertical tangent at given station."},{"n":"IsValid","d":"Checks if this object is a valid alignment."},{"n":"IsValid(Element)","d":"Checks if the element is a valid alignment."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetVCurveNormalAtStation(System.Double)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetVCurveNormalAtStation(System.Double)","title":"Alignment.GetVCurveNormalAtStation Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculate 2d (X and Y components of returned vector) vertical normal at given station.","sig":"public XYZ GetVCurveNormalAtStation(\n\tdouble station\n)"},"T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint":{"id":"T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint","title":"HorizontalCurveEndpoint Class","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Represents an endpoint (start or end) of a horizontal curve in Alignment geometry.","sig":"public class HorizontalCurveEndpoint","inherit":["SystemObject","Autodesk.Revit.DB.InfrastructureHorizontalCurveEndpoint"],"members":{"props":[{"n":"NextCurveType","d":"The HorizontalCurveType \n               of the curve which connects the endpoint to the next displayed curve.\n               If this endpoint's Station equals \n               DisplayedEndStation, returns Unknown curve type."},{"n":"PreviousCurveType","d":"The HorizontalCurveType \n               of the curve which connects the endpoint to the previous displayed curve.\n               If this endpoint's Station equals \n               DisplayedStartStation, returns Unknown curve type."},{"n":"Station","d":"The endpoint's station value."}],"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValid":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValid","title":"AlignmentStationLabel.IsValid Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Checks if this object is a valid alignment station label.","sig":"public bool IsValid()"},"Properties.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions":{"id":"Properties.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions","title":"AlignmentStationLabelOptions Properties","ns":"Autodesk.Revit.DB.Infrastructure","members":{"props":[{"n":"HasLeader","d":"Specifies if the label will have a leader. \n               The default value is true."},{"n":"LeaderEnd","d":"Specifies the leader end point, in model coordinates. \n               The default value is null.\n               When null, the end point will be the same as the Origin point, \n               driven by the Station value."},{"n":"LeaderShoulder","d":"Specifies the leader shoulder point, in model coordinates. \n               The default value is null.\n               When null, the shoulder point will be the same as the Origin point, \n               driven by the Station value."},{"n":"Station","d":"Specifies the station at which the label will be placed, in Revit internal model units (standard Imperial feet).\n               The station determines the location of the label's origin: Origin \n               by setting it to the closest point on the alignment geometry which corresponds to this station."},{"n":"TypeId","d":"Specifies the ElementId of the label type. \n               The default value is InvalidElementId. In this case, the default type id for alignment station labels in the document is used."}]}},"P:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint.NextCurveType":{"id":"P:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint.NextCurveType","title":"HorizontalCurveEndpoint.NextCurveType Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The HorizontalCurveType \n               of the curve which connects the endpoint to the next displayed curve.\n               If this endpoint's Station equals \n               DisplayedEndStation, returns Unknown curve type.","sig":"public HorizontalCurveType NextCurveType { get; }"},"T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveType":{"id":"T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveType","title":"HorizontalCurveType Enumeration","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Represents the curve types for the horizontal curves which define Alignment geometry.","sig":"public enum HorizontalCurveType"},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.#ctor":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.#ctor","title":"AlignmentStationLabelSetOptions Constructor","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Create an object with default values.","sig":"public AlignmentStationLabelSetOptions()"},"Overload:Autodesk.Revit.DB.Infrastructure.Alignment.IsValid":{"id":"Overload:Autodesk.Revit.DB.Infrastructure.Alignment.IsValid","title":"Alignment.IsValid Method","ns":"Autodesk.Revit.DB.Infrastructure"},"Overload:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValid":{"id":"Overload:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValid","title":"AlignmentStationLabel.IsValid Method","ns":"Autodesk.Revit.DB.Infrastructure"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.TypeId":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.TypeId","title":"AlignmentStationLabelOptions.TypeId Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the ElementId of the label type. \n               The default value is InvalidElementId. In this case, the default type id for alignment station labels in the document is used.","sig":"public ElementId TypeId { get; set; }","remarks":"Valid types can be found using IsValidType(Element)."},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.Offset":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.Offset","title":"AlignmentStationLabelSetOptions.Offset Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The offset of the labels from the alignment, in Revit internal paper space units (standard Imperial feet).\n               A positive offset creates labels to the right of the alignment, a negative - to the left.\n               The default value is null.\n               If null, a predefined offset value will be used, depending on the unit setting for stationing units in the document.\n               For standard imperial, the default is 1/8\".\n               For survey imperial, the default is 1/8\" (US survey).\n               For metric, the default is 5 mm.","sig":"public double? Offset { get; set; }"},"Properties.T:Autodesk.Revit.DB.Infrastructure.Alignment":{"id":"Properties.T:Autodesk.Revit.DB.Infrastructure.Alignment","title":"Alignment Properties","ns":"Autodesk.Revit.DB.Infrastructure","members":{"props":[{"n":"Description","d":"The Description of this alignment."},{"n":"DisplayedEndStation","d":"Specifies the station at which the alignment's display ends, in Revit internal model units (standard Imperial feet)."},{"n":"DisplayedStartStation","d":"Specifies the station at which the alignment's display starts, in Revit internal model units (standard Imperial feet)."},{"n":"Element","d":"The underlying DirectShape element."},{"n":"EndStation","d":"Specifies the station at which the alignment's geometric definition ends, in Revit internal model units (standard Imperial feet)."},{"n":"GUID","d":"The GUID of this alignment."},{"n":"Name","d":"The Name of this alignment."},{"n":"StartStation","d":"Specifies the station at which the alignment's geometric definition starts, in Revit internal model units (standard Imperial feet)."}]}},"M:Autodesk.Revit.DB.Infrastructure.Alignment.Get(Autodesk.Revit.DB.Document,System.Guid)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.Get(Autodesk.Revit.DB.Document,System.Guid)","title":"Alignment.Get(Document, Guid) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns an Alignment in the document given its GUID.","sig":"public static Alignment Get(\n\tDocument document,\n\tGuid guid\n)"},"P:Autodesk.Revit.DB.Infrastructure.Alignment.GUID":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.GUID","title":"Alignment.GUID Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The GUID of this alignment.","sig":"public Guid GUID { get; }"},"Methods.T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint":{"id":"Methods.T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint","title":"HorizontalCurveEndpoint Methods","ns":"Autodesk.Revit.DB.Infrastructure","members":{"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"Methods.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel":{"id":"Methods.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel","title":"AlignmentStationLabel Methods","ns":"Autodesk.Revit.DB.Infrastructure","members":{"methods":[{"n":"Create","d":"Creates an AlignmentStationLabel object along with its underlying SpotDimension element. \n               Returns null if element creation fails."},{"n":"CreateRecommendedTypeForSet","d":"Creates an element type recommended for alignment label sets and returns its ElementId."},{"n":"CreateSet","d":"Creates a collection of AlignmentStationLabel objects along with their underlying SpotDimension elements."},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"Get","d":"Returns an AlignmentStationLabel object for the given element."},{"n":"GetAlignmentStationLabels(Alignment)","d":"Returns all alignment station labels placed on the given alignment."},{"n":"GetAlignmentStationLabels(Alignment, ElementId)","d":"Returns all alignment station labels placed on the given alignment in the given view."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsRecommendedTypeForSet","d":"Checks if the element type is recommended for alignment labels in sets."},{"n":"IsValid","d":"Checks if this object is a valid alignment station label."},{"n":"IsValid(Element)","d":"Checks if the element is a valid alignment station label."},{"n":"IsValidType","d":"Checks if the type is a valid alignment station label type."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"Properties.T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint":{"id":"Properties.T:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint","title":"HorizontalCurveEndpoint Properties","ns":"Autodesk.Revit.DB.Infrastructure","members":{"props":[{"n":"NextCurveType","d":"The HorizontalCurveType \n               of the curve which connects the endpoint to the next displayed curve.\n               If this endpoint's Station equals \n               DisplayedEndStation, returns Unknown curve type."},{"n":"PreviousCurveType","d":"The HorizontalCurveType \n               of the curve which connects the endpoint to the previous displayed curve.\n               If this endpoint's Station equals \n               DisplayedStartStation, returns Unknown curve type."},{"n":"Station","d":"The endpoint's station value."}]}},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetDisplayedHorizontalCurveEndpoints":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetDisplayedHorizontalCurveEndpoints","title":"Alignment.GetDisplayedHorizontalCurveEndpoints Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns the endpoints of the alignment's horizontal curves.\n               Only the points between DisplayedStartStation \n               and DisplayedEndStation are returned.","sig":"public IList<HorizontalCurveEndpoint> GetDisplayedHorizontalCurveEndpoints()"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetVCurveTangentAtStation(System.Double)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetVCurveTangentAtStation(System.Double)","title":"Alignment.GetVCurveTangentAtStation Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculate 2d (X and Y components of returned vector) vertical tangent at given station.","sig":"public XYZ GetVCurveTangentAtStation(\n\tdouble station\n)"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetAlignments(Autodesk.Revit.DB.Document)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetAlignments(Autodesk.Revit.DB.Document)","title":"Alignment.GetAlignments(Document) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns all alignments in the given document.","sig":"public static ICollection<Alignment> GetAlignments(\n\tDocument document\n)"},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.CreateSet(Autodesk.Revit.DB.Infrastructure.Alignment,Autodesk.Revit.DB.View,Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.CreateSet(Autodesk.Revit.DB.Infrastructure.Alignment,Autodesk.Revit.DB.View,Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions)","title":"AlignmentStationLabel.CreateSet Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Creates a collection of AlignmentStationLabel objects along with their underlying SpotDimension elements.","sig":"public static ICollection<AlignmentStationLabel> CreateSet(\n\tAlignment alignment,\n\tView view,\n\tAlignmentStationLabelSetOptions options\n)"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetHCurveTangentAtStation(System.Double)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetHCurveTangentAtStation(System.Double)","title":"Alignment.GetHCurveTangentAtStation Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculate 2d (X and Y components of returned vector) horizontal tangent at given station.","sig":"public XYZ GetHCurveTangentAtStation(\n\tdouble station\n)"},"P:Autodesk.Revit.DB.Infrastructure.Alignment.EndStation":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.EndStation","title":"Alignment.EndStation Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the station at which the alignment's geometric definition ends, in Revit internal model units (standard Imperial feet).","sig":"public double EndStation { get; }","remarks":"This station may be outside the displayed range (DisplayedStartStation, DisplayedEndStation)."},"M:Autodesk.Revit.DB.Infrastructure.Alignment.IsValid":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.IsValid","title":"Alignment.IsValid Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Checks if this object is a valid alignment.","sig":"public bool IsValid()"},"Methods.T:Autodesk.Revit.DB.Infrastructure.Alignment":{"id":"Methods.T:Autodesk.Revit.DB.Infrastructure.Alignment","title":"Alignment Methods","ns":"Autodesk.Revit.DB.Infrastructure","members":{"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"Get(Element)","d":"Returns an Alignment object given a Revit alignment element."},{"n":"Get(Document, Guid)","d":"Returns an Alignment in the document given its GUID."},{"n":"GetAlignments(Document)","d":"Returns all alignments in the given document."},{"n":"GetAlignments(View)","d":"Returns all alignments visible in the given view."},{"n":"GetClosestPoint","d":"Calculates the point on the alignment's geometry which is closest to the given model point."},{"n":"GetClosestStation","d":"Calculates the alignment station closest to the given model point."},{"n":"GetDisplayedHorizontalCurveEndpoints","d":"Returns the endpoints of the alignment's horizontal curves.\n               Only the points between DisplayedStartStation \n               and DisplayedEndStation are returned."},{"n":"GetDistance","d":"Calculates the relative distance along the alignment between two stations based on their alignment distances\n               according to Revit Internal Origin Coordinate Base. The distance may be positive or negative depending on\n               the relative positions of the input stations on the alignment."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetHCurveNormalAtStation","d":"Calculate 2d (X and Y components of returned vector) horizontal normal at given station."},{"n":"GetHCurveTangentAtStation","d":"Calculate 2d (X and Y components of returned vector) horizontal tangent at given station."},{"n":"GetPointAtStation","d":"Calculates the model point for a given alignment station."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"GetVCurveNormalAtStation","d":"Calculate 2d (X and Y components of returned vector) vertical normal at given station."},{"n":"GetVCurveTangentAtStation","d":"Calculate 2d (X and Y components of returned vector) vertical tangent at given station."},{"n":"IsValid","d":"Checks if this object is a valid alignment."},{"n":"IsValid(Element)","d":"Checks if the element is a valid alignment."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"N:Autodesk.Revit.DB.Infrastructure":{"id":"N:Autodesk.Revit.DB.Infrastructure","title":"Autodesk.Revit.DB.Infrastructure Namespace","ns":"Autodesk.Revit.DB.Infrastructure"},"P:Autodesk.Revit.DB.Infrastructure.Alignment.DisplayedEndStation":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.DisplayedEndStation","title":"Alignment.DisplayedEndStation Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the station at which the alignment's display ends, in Revit internal model units (standard Imperial feet).","sig":"public double DisplayedEndStation { get; }","remarks":"This station is within the alignment's geometric definition range (StartStation, EndStation)."},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.EndStation":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.EndStation","title":"AlignmentStationLabelSetOptions.EndStation Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The ending station for creating labels in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, the station value corresponding to the alignment's DisplayedEndStation is used.","sig":"public double? EndStation { get; set; }"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.IsValid(Autodesk.Revit.DB.Element)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.IsValid(Autodesk.Revit.DB.Element)","title":"Alignment.IsValid(Element) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Checks if the element is a valid alignment.","sig":"public static bool IsValid(\n\tElement element\n)"},"P:Autodesk.Revit.DB.Infrastructure.Alignment.Name":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.Name","title":"Alignment.Name Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The Name of this alignment.","sig":"public string Name { get; }"},"Overload:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.GetAlignmentStationLabels":{"id":"Overload:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.GetAlignmentStationLabels","title":"AlignmentStationLabel.GetAlignmentStationLabels Method","ns":"Autodesk.Revit.DB.Infrastructure"},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsRecommendedTypeForSet(Autodesk.Revit.DB.Element)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsRecommendedTypeForSet(Autodesk.Revit.DB.Element)","title":"AlignmentStationLabel.IsRecommendedTypeForSet Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Checks if the element type is recommended for alignment labels in sets.","sig":"public static bool IsRecommendedTypeForSet(\n\tElement type\n)","remarks":"Can be used for finding types to be set to TypeId when creating alignment label sets with CreateSet(Alignment, View, AlignmentStationLabelSetOptions)."},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.GetAlignmentStationLabels(Autodesk.Revit.DB.Infrastructure.Alignment,Autodesk.Revit.DB.ElementId)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.GetAlignmentStationLabels(Autodesk.Revit.DB.Infrastructure.Alignment,Autodesk.Revit.DB.ElementId)","title":"AlignmentStationLabel.GetAlignmentStationLabels(Alignment, ElementId) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns all alignment station labels placed on the given alignment in the given view.","sig":"public static ICollection<AlignmentStationLabel> GetAlignmentStationLabels(\n\tAlignment alignment,\n\tElementId viewId\n)","remarks":"The resulting collection may contain both \"individual\" labels (created via Create(Alignment, View, AlignmentStationLabelOptions)) and \"labels in set\" (created via CreateSet(Alignment, View, AlignmentStationLabelSetOptions)). These labels have categories respectively OST_Alignments and OST_AlignmentStationLabelSets."},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.LeaderShoulder":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.LeaderShoulder","title":"AlignmentStationLabelOptions.LeaderShoulder Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the leader shoulder point, in model coordinates. \n               The default value is null.\n               When null, the shoulder point will be the same as the Origin point, \n               driven by the Station value.","sig":"public XYZ LeaderShoulder { get; set; }"},"P:Autodesk.Revit.DB.Infrastructure.Alignment.StartStation":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.StartStation","title":"Alignment.StartStation Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the station at which the alignment's geometric definition starts, in Revit internal model units (standard Imperial feet).","sig":"public double StartStation { get; }","remarks":"This station may be outside the displayed range (DisplayedStartStation, DisplayedEndStation)."},"P:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint.Station":{"id":"P:Autodesk.Revit.DB.Infrastructure.HorizontalCurveEndpoint.Station","title":"HorizontalCurveEndpoint.Station Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The endpoint's station value.","sig":"public double Station { get; }"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.LeaderEnd":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.LeaderEnd","title":"AlignmentStationLabelOptions.LeaderEnd Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Specifies the leader end point, in model coordinates. \n               The default value is null.\n               When null, the end point will be the same as the Origin point, \n               driven by the Station value.","sig":"public XYZ LeaderEnd { get; set; }"},"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.Interval":{"id":"P:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelSetOptions.Interval","title":"AlignmentStationLabelSetOptions.Interval Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The interval between labels to be created in the set, in Revit internal model units (standard Imperial feet).\n               The default value is null.\n               When null, a predefined interval value will be used, depending on the unit setting for stationing units in the document.\n               For standard imperial, the default is 100 ft.\n               For survey imperial, the default is 100 USft (US survey).\n               For metric, the default is 1000 m.","sig":"public double? Interval { get; set; }"},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Create(Autodesk.Revit.DB.Infrastructure.Alignment,Autodesk.Revit.DB.View,Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Create(Autodesk.Revit.DB.Infrastructure.Alignment,Autodesk.Revit.DB.View,Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions)","title":"AlignmentStationLabel.Create Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Creates an AlignmentStationLabel object along with its underlying SpotDimension element. \n               Returns null if element creation fails.","sig":"public static AlignmentStationLabel Create(\n\tAlignment alignment,\n\tView view,\n\tAlignmentStationLabelOptions options\n)"},"P:Autodesk.Revit.DB.Infrastructure.Alignment.Description":{"id":"P:Autodesk.Revit.DB.Infrastructure.Alignment.Description","title":"Alignment.Description Property","ns":"Autodesk.Revit.DB.Infrastructure","desc":"The Description of this alignment.","sig":"public string Description { get; }"},"Properties.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel":{"id":"Properties.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel","title":"AlignmentStationLabel Properties","ns":"Autodesk.Revit.DB.Infrastructure","members":{"props":[{"n":"AlignmentId","d":"The ElementId of the Alignment on which the SpotDimension is placed."},{"n":"Element","d":"The underlying SpotDimension element."},{"n":"Station","d":"The alignment station at which the SpotDimension is placed."}]}},"Methods.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions":{"id":"Methods.T:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions","title":"AlignmentStationLabelOptions Methods","ns":"Autodesk.Revit.DB.Infrastructure","members":{"methods":[{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Get(Autodesk.Revit.DB.Element)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.Get(Autodesk.Revit.DB.Element)","title":"AlignmentStationLabel.Get Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns an AlignmentStationLabel object for the given element.","sig":"public static AlignmentStationLabel Get(\n\tElement element\n)"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetHCurveNormalAtStation(System.Double)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetHCurveNormalAtStation(System.Double)","title":"Alignment.GetHCurveNormalAtStation Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Calculate 2d (X and Y components of returned vector) horizontal normal at given station.","sig":"public XYZ GetHCurveNormalAtStation(\n\tdouble station\n)"},"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetAlignments(Autodesk.Revit.DB.View)":{"id":"M:Autodesk.Revit.DB.Infrastructure.Alignment.GetAlignments(Autodesk.Revit.DB.View)","title":"Alignment.GetAlignments(View) Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Returns all alignments visible in the given view.","sig":"public static ICollection<Alignment> GetAlignments(\n\tView view\n)"},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValidType(Autodesk.Revit.DB.Element)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabel.IsValidType(Autodesk.Revit.DB.Element)","title":"AlignmentStationLabel.IsValidType Method","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Checks if the type is a valid alignment station label type.","sig":"public static bool IsValidType(\n\tElement type\n)","remarks":"Can be used for finding or types to be set to TypeId when creating alignment label sets with Create(Alignment, View, AlignmentStationLabelOptions); or types to be set to TypeId when creating alignment labels with CreateSet(Alignment, View, AlignmentStationLabelSetOptions)."},"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.#ctor(System.Double)":{"id":"M:Autodesk.Revit.DB.Infrastructure.AlignmentStationLabelOptions.#ctor(System.Double)","title":"AlignmentStationLabelOptions Constructor","ns":"Autodesk.Revit.DB.Infrastructure","desc":"Creates an object with default values.","sig":"public AlignmentStationLabelOptions(\n\tdouble station\n)"}}