{"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Assign(Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Assign(Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)","title":"PointCloudColorSettings.Assign Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Assigns values of the source settings to this object.","sig":"public void Assign(\n\tPointCloudColorSettings other\n)"},"Fields.T:Autodesk.Revit.DB.PointClouds.CloudPoint":{"id":"Fields.T:Autodesk.Revit.DB.PointClouds.CloudPoint","title":"CloudPoint Fields","ns":"Autodesk.Revit.DB.PointClouds","members":{"fields":[{"n":"Color","d":"The color"},{"n":"X","d":"The X coordinate"},{"n":"Y","d":"The Y coordinate"},{"n":"Z","d":"The Z coordinate"}]}},"Operators.T:Autodesk.Revit.DB.PointClouds.CloudPoint":{"id":"Operators.T:Autodesk.Revit.DB.PointClouds.CloudPoint","title":"CloudPoint Type Conversions","ns":"Autodesk.Revit.DB.PointClouds"},"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.GetSupportedEngines":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.GetSupportedEngines","title":"PointCloudEngineRegistry.GetSupportedEngines Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Returns a list of the identifiers supported by point cloud engines registered to Revit.","sig":"public static IList<string> GetSupportedEngines()"},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudFilter":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudFilter","title":"PointCloudFilter Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"Clone","d":"Returns a copy of the filter. The engine is permitted to copy the filter multiple times e.g. to parallelize filtering."},{"n":"Dispose","d":""},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"PrepareForCell","d":"Informs the filter that a series of points within a given cell is about to be checked."},{"n":"TestCell","d":"Checks whether a given cell, i.e. a box aligned with the XYZ axes, is inside, outside\n   or on the border of the volume of interest."},{"n":"TestPoint","d":"Checks if a point is inside the volume of interest."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.Dispose":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.Dispose","title":"PointCloudFilter.Dispose Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Releases all resources used by the PointCloudFilter","sig":"public void Dispose()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.IsEqual(Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.IsEqual(Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)","title":"PointCloudOverrideSettings.IsEqual Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Checks if the contents of two settings are equal.","sig":"public bool IsEqual(\n\tPointCloudOverrideSettings other\n)"},"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudScanOverrideSettings":{"id":"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudScanOverrideSettings","title":"PointCloudOverrides.GetPointCloudScanOverrideSettings Method","ns":"Autodesk.Revit.DB.PointClouds"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings,System.String,Autodesk.Revit.DB.Document)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings,System.String,Autodesk.Revit.DB.Document)","title":"PointCloudOverrides.SetPointCloudScanOverrideSettings(ElementId, PointCloudOverrideSettings, String, Document) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Assigns scan override settings to a particular scan within a PointCloudInstance element.","sig":"public void SetPointCloudScanOverrideSettings(\n\tElementId elementId,\n\tPointCloudOverrideSettings newSettings,\n\tstring scanTag,\n\tDocument doc\n)"},"T:Autodesk.Revit.DB.PointClouds.PointIterator":{"id":"T:Autodesk.Revit.DB.PointClouds.PointIterator","title":"PointIterator Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"A class used to iterate individual points in a PointCollection.","sig":"public class PointIterator : IEnumerator<CloudPoint>","remarks":"Points may be iterated in two different ways: In the traditional IEnumerable interface, you can iterate the resulting points directly from the PointCollection.In an unsafe interface usable only from C# and C++/CLI, you can get a pointer to the point storage of the collection and access the points directly in memory. Although you must deal with pointers directly, there may be performance improvements when traversing large buffers of points. Regardless of the approach used to obtain the points, the points are reported in the coordinate system of the point cloud. If you need the points in the coordinate system of the model, you will need to transform the point in those coordinates. The most direct way to do this is to obtain the transformation matrix from the PointCloudInstance (GetTransform()), convert the CloudPoint to an XYZ using the implicit conversion operator, and use Transform.OfPoint(XYZ).","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointIterator"],"members":{"props":[{"n":"Current","d":""},{"n":"CurrentObject","d":""},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}],"methods":[{"n":"Dispose","d":"Releases all resources used by the PointIterator"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"Free","d":"Completes lifetime of the iterator.  Call it when done using the iterator."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsDone","d":"Identifies if the iteration has reached the end of the collection."},{"n":"MoveNext","d":"Increments the iterator to the next point in the collection."},{"n":"Reset","d":"Resets the iterator to the beginning of the collection."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"T:Autodesk.Revit.DB.PointClouds.PointCloudColorEncoding":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudColorEncoding","title":"PointCloudColorEncoding Enumeration","ns":"Autodesk.Revit.DB.PointClouds","desc":"The color encodings supported by Revit point clouds.","sig":"public enum PointCloudColorEncoding"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId,System.String,Autodesk.Revit.DB.Document)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId,System.String,Autodesk.Revit.DB.Document)","title":"PointCloudOverrides.GetPointCloudRegionOverrideSettings(ElementId, String, Document) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Gets override settings assigned to a particular region within a PointCloudInstance element.","sig":"public PointCloudOverrideSettings GetPointCloudRegionOverrideSettings(\n\tElementId elementId,\n\tstring regionTag,\n\tDocument doc\n)"},"F:Autodesk.Revit.DB.PointClouds.CloudPoint.Color":{"id":"F:Autodesk.Revit.DB.PointClouds.CloudPoint.Color","title":"CloudPoint.Color Field","ns":"Autodesk.Revit.DB.PointClouds","desc":"The color","sig":"public int Color"},"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.IsValidObject":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.IsValidObject","title":"PointCloudOverrideSettings.IsValidObject Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Specifies whether the .NET object represents a valid Revit entity.","sig":"public bool IsValidObject { get; }","remarks":"If the corresponding Revit native object is destroyed, or creation of the corresponding object is undone, a managed API object containing it is no longer valid. API methods cannot be called on invalidated wrapper objects."},"M:Autodesk.Revit.DB.PointClouds.PointIterator.MoveNext":{"id":"M:Autodesk.Revit.DB.PointClouds.PointIterator.MoveNext","title":"PointIterator.MoveNext Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Increments the iterator to the next point in the collection.","sig":"public virtual bool MoveNext()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.GetModeOverride(Autodesk.Revit.DB.PointCloudColorMode)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.GetModeOverride(Autodesk.Revit.DB.PointCloudColorMode)","title":"PointCloudOverrideSettings.GetModeOverride Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Lookup color settings for the given color mode.","sig":"public PointCloudColorSettings GetModeOverride(\n\tPointCloudColorMode mode\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.ArePointCloudOverrideSettingsValid(System.String,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.ArePointCloudOverrideSettingsValid(System.String,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)","title":"PointCloudOverrides.ArePointCloudOverrideSettingsValid Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Checks if PointCloudOverrideSettings are valid","sig":"public static bool ArePointCloudOverrideSettingsValid(\n\tstring tag,\n\tPointCloudOverrideSettings settings\n)"},"T:Autodesk.Revit.DB.PointClouds.PointCloudFilterUtils":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudFilterUtils","title":"PointCloudFilterUtils Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"Utilities specific to point cloud filters.","sig":"public static class PointCloudFilterUtils","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCloudFilterUtils"],"members":{"methods":[{"n":"GetFilteredOutline","d":"Computes outline of a part of a box that satisfies given PointCloudFilter."}]}},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetOffset":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetOffset","title":"IPointCloudAccess.GetOffset Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to return the offset stored in the point cloud.","sig":"XYZ GetOffset()","remarks":"All points are assumed to be offset by the same offset vector. The offset should be expressed in the same units as used by the point coordinates (the scale conversion factor is not applied). The offset will be used by Revit if the user chooses to place an instance relative to another point cloud (the \"Auto - Origin To Last Placed\" placement option)."},"M:Autodesk.Revit.DB.PointClouds.IPointSetIterator.Free":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointSetIterator.Free","title":"IPointSetIterator.Free Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Use this method to discard any resources consumed by the iterator.  Revit will call it when done using the iterator.","sig":"void Free()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.Dispose":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.Dispose","title":"PointCloudOverrides.Dispose Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Releases all resources used by the PointCloudOverrides","sig":"public void Dispose()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)","title":"PointCloudOverrides.SetPointCloudScanOverrideSettings(ElementId, PointCloudOverrideSettings) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Assigns scan override settings to the whole PointCloudInstance element.","sig":"public void SetPointCloudScanOverrideSettings(\n\tElementId elementId,\n\tPointCloudOverrideSettings newSettings\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId)","title":"PointCloudOverrides.GetPointCloudRegionOverrideSettings(ElementId) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Gets region override settings assigned to the whole PointCloudInstance element.","sig":"public PointCloudOverrideSettings GetPointCloudRegionOverrideSettings(\n\tElementId elementId\n)"},"Methods.T:Autodesk.Revit.DB.PointClouds.IPointCloudAccess":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.IPointCloudAccess","title":"IPointCloudAccess Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"CreatePointSetIterator(PointCloudFilter, ElementId)","d":"Implement this method to return an iterator for iterating over blocks of this point cloud."},{"n":"CreatePointSetIterator(PointCloudFilter, Double, ElementId)","d":"Implement this method to return an iterator for iterating over blocks of this point cloud."},{"n":"Free","d":"Completes the lifetime of the object providing this interface."},{"n":"GetColorEncoding","d":"Returns the encoding used by points in this point cloud."},{"n":"GetExtent","d":"Implement this method to returns an object that contains the bounding box of the entire\n   point cloud, aligned to the point cloud coordinate system."},{"n":"GetName","d":"Implement this method to return the name of the point cloud that will be used when Revit needs to\n   refer to the point cloud type, e.g. in the Manage Links dialog or in the\n   Type Properties dialog."},{"n":"GetOffset","d":"Implement this method to return the offset stored in the point cloud."},{"n":"GetUnitsToFeetConversionFactor","d":"Implement this method to return the conversion factor from the units of the point cloud to feet."},{"n":"ReadPoints","d":"Implement this method so that on successive invocations it will return distinct subsets of\n   points which meet the criterion."}]}},"M:Autodesk.Revit.DB.PointClouds.CloudPoint.#ctor(System.Single,System.Single,System.Single,System.Int32)":{"id":"M:Autodesk.Revit.DB.PointClouds.CloudPoint.#ctor(System.Single,System.Single,System.Single,System.Int32)","title":"CloudPoint Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Creates a new cloud point.","sig":"public CloudPoint(\n\tfloat x,\n\tfloat y,\n\tfloat z,\n\tint color\n)"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.CreatePointSetIterator(Autodesk.Revit.DB.PointClouds.PointCloudFilter,Autodesk.Revit.DB.ElementId)":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.CreatePointSetIterator(Autodesk.Revit.DB.PointClouds.PointCloudFilter,Autodesk.Revit.DB.ElementId)","title":"IPointCloudAccess.CreatePointSetIterator(PointCloudFilter, ElementId) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to return an iterator for iterating over blocks of this point cloud.","sig":"IPointSetIterator CreatePointSetIterator(\n\tPointCloudFilter rFilter,\n\tElementId viewId\n)"},"T:Autodesk.Revit.DB.PointClouds.PointCollection":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCollection","title":"PointCollection Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"A class that represents a set of points created and returned by Revit in response to a query.","sig":"public class PointCollection : IEnumerable<CloudPoint>, \n\tIDisposable","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCollection"],"members":{"props":[{"n":"Count","d":"The number of points in this collection."},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}],"methods":[{"n":"Dispose","d":"Releases all resources used by the PointCollection"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetBasicIEnumerator","d":"Returns an enumerator that iterates through a collection."},{"n":"GetEnumerator","d":"Returns an enumerator that iterates through a collection."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetPointBufferPointer","d":"Returns an unsafe pointer to the buffer in which this collection stores the points."},{"n":"GetPointIterator","d":"Creates and returns an iterator for the points contained in this collection."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.TestPoint(Autodesk.Revit.DB.PointClouds.CloudPoint)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.TestPoint(Autodesk.Revit.DB.PointClouds.CloudPoint)","title":"PointCloudFilter.TestPoint Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Checks if a point is inside the volume of interest.","sig":"public virtual bool TestPoint(\n\tCloudPoint point\n)"},"Properties.T:Autodesk.Revit.DB.PointClouds.PointIterator":{"id":"Properties.T:Autodesk.Revit.DB.PointClouds.PointIterator","title":"PointIterator Properties","ns":"Autodesk.Revit.DB.PointClouds","members":{"props":[{"n":"Current","d":""},{"n":"CurrentObject","d":""},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}]}},"Properties.T:Autodesk.Revit.DB.PointClouds.PointCollection":{"id":"Properties.T:Autodesk.Revit.DB.PointClouds.PointCollection","title":"PointCollection Properties","ns":"Autodesk.Revit.DB.PointClouds","members":{"props":[{"n":"Count","d":"The number of points in this collection."},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.Assign(Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.Assign(Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)","title":"PointCloudOverrideSettings.Assign Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Assigns values of the source settings to this object.","sig":"public void Assign(\n\tPointCloudOverrideSettings other\n)"},"P:Autodesk.Revit.DB.PointClouds.PointCloudFilter.IsValidObject":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudFilter.IsValidObject","title":"PointCloudFilter.IsValidObject Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Specifies whether the .NET object represents a valid Revit entity.","sig":"public bool IsValidObject { get; }","remarks":"If the corresponding Revit native object is destroyed, or creation of the corresponding object is undone, a managed API object containing it is no longer valid. API methods cannot be called on invalidated wrapper objects."},"M:Autodesk.Revit.DB.PointClouds.PointCollection.Dispose":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCollection.Dispose","title":"PointCollection.Dispose Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Releases all resources used by the PointCollection","sig":"public void Dispose()"},"T:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings","title":"PointCloudOverrideSettings Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"The graphic override settings for one PointCloudInstance element or one of its scans.","sig":"public class PointCloudOverrideSettings : IDisposable","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCloudOverrideSettings"],"members":{"props":[{"n":"ColorMode","d":"The current color mode for the PointCloudInstance element or its scan."},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."},{"n":"Visible","d":"Visibility flag for point cloud scans."}],"methods":[{"n":"Assign","d":"Assigns values of the source settings to this object."},{"n":"Dispose","d":"Releases all resources used by the PointCloudOverrideSettings"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetModeOverride","d":"Lookup color settings for the given color mode."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsEqual","d":"Checks if the contents of two settings are equal."},{"n":"SetModeOverride","d":"Sets color settings for the given color mode."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetEnumerator":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetEnumerator","title":"PointCollection.GetEnumerator Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Returns an enumerator that iterates through a collection.","sig":"public virtual IEnumerator<CloudPoint> GetEnumerator()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId,System.String,Autodesk.Revit.DB.Document)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId,System.String,Autodesk.Revit.DB.Document)","title":"PointCloudOverrides.GetPointCloudScanOverrideSettings(ElementId, String, Document) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Gets override settings assigned to a particular scan within a PointCloudInstance element.","sig":"public PointCloudOverrideSettings GetPointCloudScanOverrideSettings(\n\tElementId elementId,\n\tstring scanTag,\n\tDocument doc\n)"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetExtent":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetExtent","title":"IPointCloudAccess.GetExtent Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to returns an object that contains the bounding box of the entire\n   point cloud, aligned to the point cloud coordinate system.","sig":"Outline GetExtent()","remarks":"The extents should reflect the maximum and minimum coordinates of the stored points, and not incorporate the offset."},"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetBasicIEnumerator":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetBasicIEnumerator","title":"PointCollection.GetBasicIEnumerator Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Returns an enumerator that iterates through a collection.","sig":"internal virtual IEnumerator GetBasicIEnumerator()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor(Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor(Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)","title":"PointCloudColorSettings(PointCloudColorSettings) Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Constructs a copy of source object.","sig":"public PointCloudColorSettings(\n\tPointCloudColorSettings other\n)"},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry","title":"PointCloudEngineRegistry Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"GetSupportedEngines","d":"Returns a list of the identifiers supported by point cloud engines registered to Revit."},{"n":"IsEngineFileBased","d":"Identifies if a given engine is file-based."},{"n":"RegisterPointCloudEngine","d":"Registers a new point cloud engine and associates it to a particular file extension."},{"n":"UnregisterPointCloudEngine","d":"Unregisters the point cloud engine associated to a particular identifier."}]}},"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudFilter":{"id":"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudFilter","title":"PointCloudFilter Properties","ns":"Autodesk.Revit.DB.PointClouds","members":{"props":[{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}]}},"N:Autodesk.Revit.DB.PointClouds":{"id":"N:Autodesk.Revit.DB.PointClouds","title":"Autodesk.Revit.DB.PointClouds Namespace","ns":"Autodesk.Revit.DB.PointClouds"},"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetPointIterator":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetPointIterator","title":"PointCollection.GetPointIterator Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Creates and returns an iterator for the points contained in this collection.","sig":"public PointIterator GetPointIterator()"},"P:Autodesk.Revit.DB.PointClouds.PointCollection.IsValidObject":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCollection.IsValidObject","title":"PointCollection.IsValidObject Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Specifies whether the .NET object represents a valid Revit entity.","sig":"public bool IsValidObject { get; }","remarks":"If the corresponding Revit native object is destroyed, or creation of the corresponding object is undone, a managed API object containing it is no longer valid. API methods cannot be called on invalidated wrapper objects."},"T:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings","title":"PointCloudColorSettings Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"The color settings which are applied to a PointCloudInstance element, or one of its scans.","sig":"public class PointCloudColorSettings : IDisposable","remarks":"For different color modes (PointCloudColorMode), the color settings mean different things: for single color, color1 means the display colorfor other modes (intensity, elevation), color1 and color2 form a gradient from min to maxfor no overrides and normals, color1 and color2 are not used","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCloudColorSettings"],"members":{"props":[{"n":"Color1","d":"Color 1"},{"n":"Color2","d":"Color 2"},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}],"methods":[{"n":"Assign","d":"Assigns values of the source settings to this object."},{"n":"Dispose","d":"Releases all resources used by the PointCloudColorSettings"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsEqual","d":"Check if the contents of two settings are equal."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.PointClouds.PointIterator.IsDone":{"id":"M:Autodesk.Revit.DB.PointClouds.PointIterator.IsDone","title":"PointIterator.IsDone Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Identifies if the iteration has reached the end of the collection.","sig":"public bool IsDone()"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.ReadPoints(Autodesk.Revit.DB.PointClouds.PointCloudFilter,Autodesk.Revit.DB.ElementId,System.IntPtr,System.Int32)":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.ReadPoints(Autodesk.Revit.DB.PointClouds.PointCloudFilter,Autodesk.Revit.DB.ElementId,System.IntPtr,System.Int32)","title":"IPointCloudAccess.ReadPoints Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method so that on successive invocations it will return distinct subsets of\n   points which meet the criterion.","sig":"int ReadPoints(\n\tPointCloudFilter rFilter,\n\tElementId viewId,\n\tIntPtr buffer,\n\tint nBufferSize\n)"},"P:Autodesk.Revit.DB.PointClouds.PointCollection.Count":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCollection.Count","title":"PointCollection.Count Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"The number of points in this collection.","sig":"public int Count { get; }"},"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings":{"id":"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings","title":"PointCloudColorSettings Properties","ns":"Autodesk.Revit.DB.PointClouds","members":{"props":[{"n":"Color1","d":"Color 1"},{"n":"Color2","d":"Color 2"},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.Clone":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.Clone","title":"PointCloudFilter.Clone Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Returns a copy of the filter. The engine is permitted to copy the filter multiple times e.g. to parallelize filtering.","sig":"public PointCloudFilter Clone()"},"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.ColorMode":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.ColorMode","title":"PointCloudOverrideSettings.ColorMode Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"The current color mode for the PointCloudInstance element or its scan.","sig":"public PointCloudColorMode ColorMode { get; set; }"},"F:Autodesk.Revit.DB.PointClouds.CloudPoint.X":{"id":"F:Autodesk.Revit.DB.PointClouds.CloudPoint.X","title":"CloudPoint.X Field","ns":"Autodesk.Revit.DB.PointClouds","desc":"The X coordinate","sig":"public float X"},"Overload:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory.CreateMultiPlaneFilter":{"id":"Overload:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory.CreateMultiPlaneFilter","title":"PointCloudFilterFactory.CreateMultiPlaneFilter Method","ns":"Autodesk.Revit.DB.PointClouds"},"M:Autodesk.Revit.DB.PointClouds.PointIterator.Reset":{"id":"M:Autodesk.Revit.DB.PointClouds.PointIterator.Reset","title":"PointIterator.Reset Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Resets the iterator to the beginning of the collection.","sig":"public virtual void Reset()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.IsEqual(Autodesk.Revit.DB.PointClouds.PointCloudOverrides)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.IsEqual(Autodesk.Revit.DB.PointClouds.PointCloudOverrides)","title":"PointCloudOverrides.IsEqual Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Check if the contents of two overrides are equal.","sig":"public bool IsEqual(\n\tPointCloudOverrides other\n)"},"M:Autodesk.Revit.DB.PointClouds.PointIterator.Dispose":{"id":"M:Autodesk.Revit.DB.PointClouds.PointIterator.Dispose","title":"PointIterator.Dispose Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Releases all resources used by the PointIterator","sig":"public void Dispose()"},"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.Visible":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.Visible","title":"PointCloudOverrideSettings.Visible Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Visibility flag for point cloud scans.","sig":"public bool Visible { get; set; }","remarks":"This flag is used only for visibility of point cloud scans because the visibility of the whole point cloud element is managed as for other elements hidden in the view."},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.TestCell(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.TestCell(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)","title":"PointCloudFilter.TestCell Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Checks whether a given cell, i.e. a box aligned with the XYZ axes, is inside, outside\n   or on the border of the volume of interest.","sig":"public int TestCell(\n\tXYZ min,\n\tXYZ max\n)"},"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudScanOverrideSettings":{"id":"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudScanOverrideSettings","title":"PointCloudOverrides.SetPointCloudScanOverrideSettings Method","ns":"Autodesk.Revit.DB.PointClouds"},"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Dispose":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Dispose","title":"PointCloudColorSettings.Dispose Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Releases all resources used by the PointCloudColorSettings","sig":"public void Dispose()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.IsEngineFileBased(System.String)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.IsEngineFileBased(System.String)","title":"PointCloudEngineRegistry.IsEngineFileBased Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Identifies if a given engine is file-based.","sig":"public static bool IsEngineFileBased(\n\tstring identifier\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.#ctor":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.#ctor","title":"PointCloudOverrides Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Constructs empty overrides object.","sig":"public PointCloudOverrides()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.PrepareForCell(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.Int32)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilter.PrepareForCell(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.Int32)","title":"PointCloudFilter.PrepareForCell Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Informs the filter that a series of points within a given cell is about to be checked.","sig":"public void PrepareForCell(\n\tXYZ min,\n\tXYZ max,\n\tint numTests\n)","remarks":"This is a performance hook that the filter can use to minimize computational work per TestPoint() call within a given cell. The engine should guarantee that all points passed to TestPoint() calls will fall inside the (min, max) box specified here. This promise must be in effect until the next PrepareForCell() call."},"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor(Autodesk.Revit.DB.PointCloudColorMode)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor(Autodesk.Revit.DB.PointCloudColorMode)","title":"PointCloudColorSettings(PointCloudColorMode) Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Constructs color settings object with default color for given color mode.","sig":"public PointCloudColorSettings(\n\tPointCloudColorMode mode\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor","title":"PointCloudColorSettings Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Constructs color settings object with default colors.","sig":"public PointCloudColorSettings()"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetColorEncoding":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetColorEncoding","title":"IPointCloudAccess.GetColorEncoding Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Returns the encoding used by points in this point cloud.","sig":"PointCloudColorEncoding GetColorEncoding()"},"Methods.T:Autodesk.Revit.DB.PointClouds.CloudPoint":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.CloudPoint","title":"CloudPoint Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"Equals","d":"Indicates whether this instance and a specified object are equal.(Inherited from ValueType)"},{"n":"GetHashCode","d":"Returns the hash code for this instance.(Inherited from ValueType)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns the fully qualified type name of this instance.(Inherited from ValueType)"}]}},"F:Autodesk.Revit.DB.PointClouds.CloudPoint.Y":{"id":"F:Autodesk.Revit.DB.PointClouds.CloudPoint.Y","title":"CloudPoint.Y Field","ns":"Autodesk.Revit.DB.PointClouds","desc":"The Y coordinate","sig":"public float Y"},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory.CreateMultiPlaneFilter(System.Collections.Generic.IList{Autodesk.Revit.DB.Plane},System.Int32)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory.CreateMultiPlaneFilter(System.Collections.Generic.IList{Autodesk.Revit.DB.Plane},System.Int32)","title":"PointCloudFilterFactory.CreateMultiPlaneFilter(IList<Plane>, Int32) Method","ns":"Autodesk.Revit.DB.PointClouds","sig":"public static PointCloudFilter CreateMultiPlaneFilter(\n\tIList<Plane> planes,\n\tint exactPlaneCount\n)"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetName":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetName","title":"IPointCloudAccess.GetName Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to return the name of the point cloud that will be used when Revit needs to\n   refer to the point cloud type, e.g. in the Manage Links dialog or in the\n   Type Properties dialog.","sig":"string GetName()"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudEngine.Free":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudEngine.Free","title":"IPointCloudEngine.Free Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Revit will call this method when done using the engine.","sig":"void Free()"},"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.IsValidObject":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.IsValidObject","title":"PointCloudOverrides.IsValidObject Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Specifies whether the .NET object represents a valid Revit entity.","sig":"public bool IsValidObject { get; }","remarks":"If the corresponding Revit native object is destroyed, or creation of the corresponding object is undone, a managed API object containing it is no longer valid. API methods cannot be called on invalidated wrapper objects."},"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudRegionOverrideSettings":{"id":"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudRegionOverrideSettings","title":"PointCloudOverrides.GetPointCloudRegionOverrideSettings Method","ns":"Autodesk.Revit.DB.PointClouds"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.#ctor":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.#ctor","title":"PointCloudOverrideSettings Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Constructs a settings object with default values.","sig":"public PointCloudOverrideSettings()"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)","title":"PointCloudOverrides.SetPointCloudRegionOverrideSettings(ElementId, PointCloudOverrideSettings) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Assigns region override settings to the whole PointCloudInstance element.","sig":"public void SetPointCloudRegionOverrideSettings(\n\tElementId elementId,\n\tPointCloudOverrideSettings newSettings\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetPointBufferPointer":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCollection.GetPointBufferPointer","title":"PointCollection.GetPointBufferPointer Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Returns an unsafe pointer to the buffer in which this collection stores the points.","sig":"public IntPtr GetPointBufferPointer()"},"Overload:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.CreatePointSetIterator":{"id":"Overload:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.CreatePointSetIterator","title":"IPointCloudAccess.CreatePointSetIterator Method","ns":"Autodesk.Revit.DB.PointClouds"},"P:Autodesk.Revit.DB.PointClouds.PointIterator.Current":{"id":"P:Autodesk.Revit.DB.PointClouds.PointIterator.Current","title":"PointIterator.Current Property","ns":"Autodesk.Revit.DB.PointClouds","sig":"public virtual CloudPoint Current { get; }"},"M:Autodesk.Revit.DB.PointClouds.CloudPoint.op_Implicit(Autodesk.Revit.DB.PointClouds.CloudPoint)~Autodesk.Revit.DB.XYZ":{"id":"M:Autodesk.Revit.DB.PointClouds.CloudPoint.op_Implicit(Autodesk.Revit.DB.PointClouds.CloudPoint)~Autodesk.Revit.DB.XYZ","title":"CloudPoint Implicit Conversion (CloudPoint to XYZ)","ns":"Autodesk.Revit.DB.PointClouds","desc":"Creates an XYZ object from this point cloud.","sig":"public static implicit operator XYZ (\n\tCloudPoint cp\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.#ctor(Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.#ctor(Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings)","title":"PointCloudOverrideSettings(PointCloudOverrideSettings) Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Constructs a copy of source object.","sig":"public PointCloudOverrideSettings(\n\tPointCloudOverrideSettings other\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.RegisterPointCloudEngine(System.String,Autodesk.Revit.DB.PointClouds.IPointCloudEngine,System.Boolean)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.RegisterPointCloudEngine(System.String,Autodesk.Revit.DB.PointClouds.IPointCloudEngine,System.Boolean)","title":"PointCloudEngineRegistry.RegisterPointCloudEngine Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Registers a new point cloud engine and associates it to a particular file extension.","sig":"public static void RegisterPointCloudEngine(\n\tstring identifier,\n\tIPointCloudEngine engine,\n\tbool isFileBased\n)"},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilterUtils.GetFilteredOutline(Autodesk.Revit.DB.PointClouds.PointCloudFilter,Autodesk.Revit.DB.Outline)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilterUtils.GetFilteredOutline(Autodesk.Revit.DB.PointClouds.PointCloudFilter,Autodesk.Revit.DB.Outline)","title":"PointCloudFilterUtils.GetFilteredOutline Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Computes outline of a part of a box that satisfies given PointCloudFilter.","sig":"public static Outline GetFilteredOutline(\n\tPointCloudFilter filter,\n\tOutline box\n)"},"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings":{"id":"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings","title":"PointCloudOverrideSettings Properties","ns":"Autodesk.Revit.DB.PointClouds","members":{"props":[{"n":"ColorMode","d":"The current color mode for the PointCloudInstance element or its scan."},{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."},{"n":"Visible","d":"Visibility flag for point cloud scans."}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.IsEqual(Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.IsEqual(Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)","title":"PointCloudColorSettings.IsEqual Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Check if the contents of two settings are equal.","sig":"public bool IsEqual(\n\tPointCloudColorSettings other\n)"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudEngine.CreatePointCloudAccess(System.String)":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudEngine.CreatePointCloudAccess(System.String)","title":"IPointCloudEngine.CreatePointCloudAccess Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to construct the IPointCloudAccess interface for the point cloud designated by\n   the identifier.  This method is called once during the creation of a PointCloudType.","sig":"IPointCloudAccess CreatePointCloudAccess(\n\tstring identifier\n)","remarks":"The instance of the returned IPointCloudAccess is then used by Revit to display instances of the point cloud in Revit graphics and in the user interface."},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory","title":"PointCloudFilterFactory Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"CreateMultiPlaneFilter(IListPlane)","d":""},{"n":"CreateMultiPlaneFilter(IListPlane, Int32)","d":""}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.Dispose":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.Dispose","title":"PointCloudOverrideSettings.Dispose Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Releases all resources used by the PointCloudOverrideSettings","sig":"public void Dispose()"},"M:Autodesk.Revit.DB.PointClouds.PointIterator.Free":{"id":"M:Autodesk.Revit.DB.PointClouds.PointIterator.Free","title":"PointIterator.Free Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Completes lifetime of the iterator.  Call it when done using the iterator.","sig":"public void Free()"},"P:Autodesk.Revit.DB.PointClouds.PointIterator.CurrentObject":{"id":"P:Autodesk.Revit.DB.PointClouds.PointIterator.CurrentObject","title":"PointIterator.CurrentObject Property","ns":"Autodesk.Revit.DB.PointClouds","sig":"public Object CurrentObject { get; }"},"T:Autodesk.Revit.DB.PointClouds.PointCloudOverrides":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudOverrides","title":"PointCloudOverrides Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"Graphic overrides that are stored by a view to be applied to a PointCloudInstance element, or a scan within the element.","sig":"public class PointCloudOverrides : IDisposable","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCloudOverrides"],"members":{"props":[{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}],"methods":[{"n":"ArePointCloudOverrideSettingsValid","d":"Checks if PointCloudOverrideSettings are valid"},{"n":"Assign","d":"Assigns values of the source overrides to this object."},{"n":"Dispose","d":"Releases all resources used by the PointCloudOverrides"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetPointCloudRegionOverrideSettings(ElementId)","d":"Gets region override settings assigned to the whole PointCloudInstance element."},{"n":"GetPointCloudRegionOverrideSettings(ElementId, String, Document)","d":"Gets override settings assigned to a particular region within a PointCloudInstance element."},{"n":"GetPointCloudScanOverrideSettings(ElementId)","d":"Gets scan override settings assigned to the whole PointCloudInstance element."},{"n":"GetPointCloudScanOverrideSettings(ElementId, String, Document)","d":"Gets override settings assigned to a particular scan within a PointCloudInstance element."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsEqual","d":"Check if the contents of two overrides are equal."},{"n":"SetPointCloudRegionOverrideSettings(ElementId, PointCloudOverrideSettings)","d":"Assigns region override settings to the whole PointCloudInstance element."},{"n":"SetPointCloudRegionOverrideSettings(ElementId, PointCloudOverrideSettings, String, Document)","d":"Assigns override settings to a particular region within a PointCloudInstance element."},{"n":"SetPointCloudScanOverrideSettings(ElementId, PointCloudOverrideSettings)","d":"Assigns scan override settings to the whole PointCloudInstance element."},{"n":"SetPointCloudScanOverrideSettings(ElementId, PointCloudOverrideSettings, String, Document)","d":"Assigns scan override settings to a particular scan within a PointCloudInstance element."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"T:Autodesk.Revit.DB.PointClouds.IPointCloudEngine":{"id":"T:Autodesk.Revit.DB.PointClouds.IPointCloudEngine","title":"IPointCloudEngine Interface","ns":"Autodesk.Revit.DB.PointClouds","desc":"An interface that controls the behavior of the link from Revit to a custom Point Cloud Engine.","sig":"public interface IPointCloudEngine","remarks":"An instance of this interface should be created by the engine provider and registered with the PointCloudEnginesRegistry. The engine may associated with a particular file name extension during registration (for example, Revit supplies a built-in engine for working with files with the extension \"rcs\" or \"rcp\"). Alternatively, the engine may be associated with an identifier which is not expected to the be the extension of a particular file.","members":{"methods":[{"n":"CreatePointCloudAccess","d":"Implement this method to construct the IPointCloudAccess interface for the point cloud designated by\n   the identifier.  This method is called once during the creation of a PointCloudType."},{"n":"Free","d":"Revit will call this method when done using the engine."}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor(Autodesk.Revit.DB.Color,Autodesk.Revit.DB.Color)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor(Autodesk.Revit.DB.Color,Autodesk.Revit.DB.Color)","title":"PointCloudColorSettings(Color, Color) Constructor","ns":"Autodesk.Revit.DB.PointClouds","desc":"Constructs color settings object from given colors.","sig":"public PointCloudColorSettings(\n\tColor color1,\n\tColor color2\n)"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.CreatePointSetIterator(Autodesk.Revit.DB.PointClouds.PointCloudFilter,System.Double,Autodesk.Revit.DB.ElementId)":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.CreatePointSetIterator(Autodesk.Revit.DB.PointClouds.PointCloudFilter,System.Double,Autodesk.Revit.DB.ElementId)","title":"IPointCloudAccess.CreatePointSetIterator(PointCloudFilter, Double, ElementId) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to return an iterator for iterating over blocks of this point cloud.","sig":"IPointSetIterator CreatePointSetIterator(\n\tPointCloudFilter rFilter,\n\tdouble density,\n\tElementId viewId\n)"},"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrides":{"id":"Properties.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrides","title":"PointCloudOverrides Properties","ns":"Autodesk.Revit.DB.PointClouds","members":{"props":[{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}]}},"Methods.T:Autodesk.Revit.DB.PointClouds.PointIterator":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointIterator","title":"PointIterator Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"Dispose","d":""},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"Free","d":"Completes lifetime of the iterator.  Call it when done using the iterator."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsDone","d":"Identifies if the iteration has reached the end of the collection."},{"n":"MoveNext","d":"Increments the iterator to the next point in the collection."},{"n":"Reset","d":"Resets the iterator to the beginning of the collection."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudRegionOverrideSettings":{"id":"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudRegionOverrideSettings","title":"PointCloudOverrides.SetPointCloudRegionOverrideSettings Method","ns":"Autodesk.Revit.DB.PointClouds"},"T:Autodesk.Revit.DB.PointClouds.CloudPoint":{"id":"T:Autodesk.Revit.DB.PointClouds.CloudPoint","title":"CloudPoint Structure","ns":"Autodesk.Revit.DB.PointClouds","desc":"Represents a point obtained from a Point cloud.","sig":"public struct CloudPoint","inherit":["SystemObject","SystemValueType","Autodesk.Revit.DB.PointCloudsCloudPoint"],"members":{"methods":[{"n":"Equals","d":"Indicates whether this instance and a specified object are equal.(Inherited from ValueType)"},{"n":"GetHashCode","d":"Returns the hash code for this instance.(Inherited from ValueType)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns the fully qualified type name of this instance.(Inherited from ValueType)"}],"fields":[{"n":"Color","d":"The color"},{"n":"X","d":"The X coordinate"},{"n":"Y","d":"The Y coordinate"},{"n":"Z","d":"The Z coordinate"}]}},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCollection":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCollection","title":"PointCollection Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"Dispose","d":""},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetBasicIEnumerator","d":"Returns an enumerator that iterates through a collection."},{"n":"GetEnumerator","d":"Returns an enumerator that iterates through a collection."},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetPointBufferPointer","d":"Returns an unsafe pointer to the buffer in which this collection stores the points."},{"n":"GetPointIterator","d":"Creates and returns an iterator for the points contained in this collection."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"T:Autodesk.Revit.DB.PointClouds.PointCloudFilter":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudFilter","title":"PointCloudFilter Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"A class used to describe the criteria an application desires when obtaining members of a point cloud.","sig":"public class PointCloudFilter : IDisposable","remarks":"Client applications which wish to obtain points from a point cloud will have to create a PointCloudFilter to define the volume of interest (see PointCloudFilterFactory). Engine implementations will need to use the methods contained within the point cloud to determine which points to return to Revit.","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCloudFilter"],"members":{"props":[{"n":"IsValidObject","d":"Specifies whether the .NET object represents a valid Revit entity."}],"methods":[{"n":"Clone","d":"Returns a copy of the filter. The engine is permitted to copy the filter multiple times e.g. to parallelize filtering."},{"n":"Dispose","d":"Releases all resources used by the PointCloudFilter"},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"PrepareForCell","d":"Informs the filter that a series of points within a given cell is about to be checked."},{"n":"TestCell","d":"Checks whether a given cell, i.e. a box aligned with the XYZ axes, is inside, outside\n   or on the border of the volume of interest."},{"n":"TestPoint","d":"Checks if a point is inside the volume of interest."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.UnregisterPointCloudEngine(System.String)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry.UnregisterPointCloudEngine(System.String)","title":"PointCloudEngineRegistry.UnregisterPointCloudEngine Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Unregisters the point cloud engine associated to a particular identifier.","sig":"public static void UnregisterPointCloudEngine(\n\tstring identifier\n)"},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudFilterUtils":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudFilterUtils","title":"PointCloudFilterUtils Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"GetFilteredOutline","d":"Computes outline of a part of a box that satisfies given PointCloudFilter."}]}},"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.#ctor":{"id":"Overload:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.#ctor","title":"PointCloudOverrideSettings Constructor","ns":"Autodesk.Revit.DB.PointClouds"},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings","title":"PointCloudOverrideSettings Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"Assign","d":"Assigns values of the source settings to this object."},{"n":"Dispose","d":""},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetModeOverride","d":"Lookup color settings for the given color mode."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsEqual","d":"Checks if the contents of two settings are equal."},{"n":"SetModeOverride","d":"Sets color settings for the given color mode."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.SetModeOverride(Autodesk.Revit.DB.PointCloudColorMode,Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings.SetModeOverride(Autodesk.Revit.DB.PointCloudColorMode,Autodesk.Revit.DB.PointClouds.PointCloudColorSettings)","title":"PointCloudOverrideSettings.SetModeOverride Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Sets color settings for the given color mode.","sig":"public void SetModeOverride(\n\tPointCloudColorMode mode,\n\tPointCloudColorSettings colorSettings\n)"},"T:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudEngineRegistry","title":"PointCloudEngineRegistry Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"This class supports registration of custom Point Cloud Engines in a Revit session.","sig":"public static class PointCloudEngineRegistry","remarks":"This class is the start point for engine providers. A custom engine implementation consists of the following: An implementation of IPointCloudEngine registered to Revit via the PointCloudEngineRegistry.An implementation of IPointCloudAccess coded to respond to inquiries from Revit regarding the properties of a single point cloud.An implementation of IPointSetIterator code to return sets of points to Revit when requested. Engine implementations may be file-based or non-file-based: File-based implementations require that each point cloud be mapped to a single file on disk. Revit will allow users to create new point cloud instances in a document directly by selecting point cloud files whose extension matches the engine identifier. These files are treated as external links in Revit and may be reloaded and remapped when necessary from the Manage Links dialog. Non-file-based engine implementations may obtain point clouds from anywhere (e.g. from a database, from a server, or from one part of a larger aggregate file). Because there is no file that the user may select, Revit's user interface will not allow a user to create a point cloud of this type. The engine provider should supply a custom command using PointCloudType.Create() and PointCloudInstance.Create() to create and place point clouds of this type. The Manage Links dialog will show the point clouds of this type, but since there is no file associated to the point cloud, the user cannot manage, reload or remap point clouds of this type.Regardless of the type of engine used, the implementation must supply enough information to Revit to display the contents of the point cloud. There are two ReadPoints methods which must be implemented: IPointCloudAccess.ReadPoints() - this provides a single set of points in a one-time call from Revit. Revit uses this during some display activities including selection prehighlighting. It is also possible for API clients to call this method directly (via PointCloudInstance.GetPoints()).IPointSetIterator.ReadPoints() - this provides a subset of points as a part of a larger iteration of points in the cloud. Revit uses this method during normal display of the point cloud; quantities of points will be requested repeatedly until it obtains enough points or until something in the display changes. The engine implementation must keep track of which points have been returned to Revit during any given point set iteration.","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCloudEngineRegistry"],"members":{"methods":[{"n":"GetSupportedEngines","d":"Returns a list of the identifiers supported by point cloud engines registered to Revit."},{"n":"IsEngineFileBased","d":"Identifies if a given engine is file-based."},{"n":"RegisterPointCloudEngine","d":"Registers a new point cloud engine and associates it to a particular file extension."},{"n":"UnregisterPointCloudEngine","d":"Unregisters the point cloud engine associated to a particular identifier."}]}},"T:Autodesk.Revit.DB.PointClouds.IPointCloudAccess":{"id":"T:Autodesk.Revit.DB.PointClouds.IPointCloudAccess","title":"IPointCloudAccess Interface","ns":"Autodesk.Revit.DB.PointClouds","desc":"An interface that provides functionality for working with an individual\n   Point Cloud.","sig":"public interface IPointCloudAccess","remarks":"An instance of this interface is obtained from the associated point cloud engine when the engine's CreatePointCloudAccess method is called.An instance of this class will be requested by Revit when drawing the point cloud in the view. For performance reasons, when rendering every frame Revit asks the engine to fetch the necessary points split into multiple batches. The number of batches requested depends on the view: the smaller the projection of the cloud bounding box on the screen the fewer batches Revit requests. Revit assumes that each batch contains points uniformly distributed over the visible part of the cloud (\"visible\" as defined by the filter). Thus, the points supplied by the engine should not be geometrically distinct (e.g. divided into multiple independent volumes, because at distant zoom levels Revit will only request a few batches and only part of the cloud will be displayed.","members":{"methods":[{"n":"CreatePointSetIterator(PointCloudFilter, ElementId)","d":"Implement this method to return an iterator for iterating over blocks of this point cloud."},{"n":"CreatePointSetIterator(PointCloudFilter, Double, ElementId)","d":"Implement this method to return an iterator for iterating over blocks of this point cloud."},{"n":"Free","d":"Completes the lifetime of the object providing this interface."},{"n":"GetColorEncoding","d":"Returns the encoding used by points in this point cloud."},{"n":"GetExtent","d":"Implement this method to returns an object that contains the bounding box of the entire\n   point cloud, aligned to the point cloud coordinate system."},{"n":"GetName","d":"Implement this method to return the name of the point cloud that will be used when Revit needs to\n   refer to the point cloud type, e.g. in the Manage Links dialog or in the\n   Type Properties dialog."},{"n":"GetOffset","d":"Implement this method to return the offset stored in the point cloud."},{"n":"GetUnitsToFeetConversionFactor","d":"Implement this method to return the conversion factor from the units of the point cloud to feet."},{"n":"ReadPoints","d":"Implement this method so that on successive invocations it will return distinct subsets of\n   points which meet the criterion."}]}},"P:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.IsValidObject":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.IsValidObject","title":"PointCloudColorSettings.IsValidObject Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Specifies whether the .NET object represents a valid Revit entity.","sig":"public bool IsValidObject { get; }","remarks":"If the corresponding Revit native object is destroyed, or creation of the corresponding object is undone, a managed API object containing it is no longer valid. API methods cannot be called on invalidated wrapper objects."},"P:Autodesk.Revit.DB.PointClouds.PointIterator.IsValidObject":{"id":"P:Autodesk.Revit.DB.PointClouds.PointIterator.IsValidObject","title":"PointIterator.IsValidObject Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Specifies whether the .NET object represents a valid Revit entity.","sig":"public bool IsValidObject { get; }","remarks":"If the corresponding Revit native object is destroyed, or creation of the corresponding object is undone, a managed API object containing it is no longer valid. API methods cannot be called on invalidated wrapper objects."},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings,System.String,Autodesk.Revit.DB.Document)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.SetPointCloudRegionOverrideSettings(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.PointClouds.PointCloudOverrideSettings,System.String,Autodesk.Revit.DB.Document)","title":"PointCloudOverrides.SetPointCloudRegionOverrideSettings(ElementId, PointCloudOverrideSettings, String, Document) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Assigns override settings to a particular region within a PointCloudInstance element.","sig":"public void SetPointCloudRegionOverrideSettings(\n\tElementId elementId,\n\tPointCloudOverrideSettings newSettings,\n\tstring regionTag,\n\tDocument doc\n)"},"P:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Color1":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Color1","title":"PointCloudColorSettings.Color1 Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Color 1","sig":"public Color Color1 { get; }"},"Methods.T:Autodesk.Revit.DB.PointClouds.IPointCloudEngine":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.IPointCloudEngine","title":"IPointCloudEngine Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"CreatePointCloudAccess","d":"Implement this method to construct the IPointCloudAccess interface for the point cloud designated by\n   the identifier.  This method is called once during the creation of a PointCloudType."},{"n":"Free","d":"Revit will call this method when done using the engine."}]}},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrides":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudOverrides","title":"PointCloudOverrides Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"ArePointCloudOverrideSettingsValid","d":"Checks if PointCloudOverrideSettings are valid"},{"n":"Assign","d":"Assigns values of the source overrides to this object."},{"n":"Dispose","d":""},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetPointCloudRegionOverrideSettings(ElementId)","d":"Gets region override settings assigned to the whole PointCloudInstance element."},{"n":"GetPointCloudRegionOverrideSettings(ElementId, String, Document)","d":"Gets override settings assigned to a particular region within a PointCloudInstance element."},{"n":"GetPointCloudScanOverrideSettings(ElementId)","d":"Gets scan override settings assigned to the whole PointCloudInstance element."},{"n":"GetPointCloudScanOverrideSettings(ElementId, String, Document)","d":"Gets override settings assigned to a particular scan within a PointCloudInstance element."},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsEqual","d":"Check if the contents of two overrides are equal."},{"n":"SetPointCloudRegionOverrideSettings(ElementId, PointCloudOverrideSettings)","d":"Assigns region override settings to the whole PointCloudInstance element."},{"n":"SetPointCloudRegionOverrideSettings(ElementId, PointCloudOverrideSettings, String, Document)","d":"Assigns override settings to a particular region within a PointCloudInstance element."},{"n":"SetPointCloudScanOverrideSettings(ElementId, PointCloudOverrideSettings)","d":"Assigns scan override settings to the whole PointCloudInstance element."},{"n":"SetPointCloudScanOverrideSettings(ElementId, PointCloudOverrideSettings, String, Document)","d":"Assigns scan override settings to a particular scan within a PointCloudInstance element."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"Overload:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor":{"id":"Overload:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.#ctor","title":"PointCloudColorSettings Constructor","ns":"Autodesk.Revit.DB.PointClouds"},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.Free":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.Free","title":"IPointCloudAccess.Free Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Completes the lifetime of the object providing this interface.","sig":"void Free()","remarks":"Calling this function indicates that the IPointCloudAccess interface is not going to be used after the call returns, and the provider of the interface can dispose of all allocated resources."},"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetUnitsToFeetConversionFactor":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointCloudAccess.GetUnitsToFeetConversionFactor","title":"IPointCloudAccess.GetUnitsToFeetConversionFactor Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to return the conversion factor from the units of the point cloud to feet.","sig":"double GetUnitsToFeetConversionFactor()"},"Methods.T:Autodesk.Revit.DB.PointClouds.IPointSetIterator":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.IPointSetIterator","title":"IPointSetIterator Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"Free","d":"Use this method to discard any resources consumed by the iterator.  Revit will call it when done using the iterator."},{"n":"ReadPoints","d":"Implement this method to fill the provided buffer with points up to the number of maximum points for\n   which the buffer was allocated."}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.GetPointCloudScanOverrideSettings(Autodesk.Revit.DB.ElementId)","title":"PointCloudOverrides.GetPointCloudScanOverrideSettings(ElementId) Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Gets scan override settings assigned to the whole PointCloudInstance element.","sig":"public PointCloudOverrideSettings GetPointCloudScanOverrideSettings(\n\tElementId elementId\n)"},"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings":{"id":"Methods.T:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings","title":"PointCloudColorSettings Methods","ns":"Autodesk.Revit.DB.PointClouds","members":{"methods":[{"n":"Assign","d":"Assigns values of the source settings to this object."},{"n":"Dispose","d":""},{"n":"Equals","d":"Determines whether the specified object is equal to the current object.(Inherited from Object)"},{"n":"GetHashCode","d":"Serves as the default hash function.(Inherited from Object)"},{"n":"GetType","d":"Gets the Type of the current instance.(Inherited from Object)"},{"n":"IsEqual","d":"Check if the contents of two settings are equal."},{"n":"ToString","d":"Returns a string that represents the current object.(Inherited from Object)"}]}},"F:Autodesk.Revit.DB.PointClouds.CloudPoint.Z":{"id":"F:Autodesk.Revit.DB.PointClouds.CloudPoint.Z","title":"CloudPoint.Z Field","ns":"Autodesk.Revit.DB.PointClouds","desc":"The Z coordinate","sig":"public float Z"},"T:Autodesk.Revit.DB.PointClouds.IPointSetIterator":{"id":"T:Autodesk.Revit.DB.PointClouds.IPointSetIterator","title":"IPointSetIterator Interface","ns":"Autodesk.Revit.DB.PointClouds","desc":"An interface that Revit will call when iterating through sets of points on the engine.","sig":"public interface IPointSetIterator","remarks":"An instance of this interface is obtained from the Point Cloud engine when the engine's CreatePointSetIterator method is called.","members":{"methods":[{"n":"Free","d":"Use this method to discard any resources consumed by the iterator.  Revit will call it when done using the iterator."},{"n":"ReadPoints","d":"Implement this method to fill the provided buffer with points up to the number of maximum points for\n   which the buffer was allocated."}]}},"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.Assign(Autodesk.Revit.DB.PointClouds.PointCloudOverrides)":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudOverrides.Assign(Autodesk.Revit.DB.PointClouds.PointCloudOverrides)","title":"PointCloudOverrides.Assign Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Assigns values of the source overrides to this object.","sig":"public void Assign(\n\tPointCloudOverrides other\n)"},"M:Autodesk.Revit.DB.PointClouds.IPointSetIterator.ReadPoints(System.IntPtr,System.Int32)":{"id":"M:Autodesk.Revit.DB.PointClouds.IPointSetIterator.ReadPoints(System.IntPtr,System.Int32)","title":"IPointSetIterator.ReadPoints Method","ns":"Autodesk.Revit.DB.PointClouds","desc":"Implement this method to fill the provided buffer with points up to the number of maximum points for\n   which the buffer was allocated.","sig":"int ReadPoints(\n\tIntPtr buffer,\n\tint bufferSize\n)"},"P:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Color2":{"id":"P:Autodesk.Revit.DB.PointClouds.PointCloudColorSettings.Color2","title":"PointCloudColorSettings.Color2 Property","ns":"Autodesk.Revit.DB.PointClouds","desc":"Color 2","sig":"public Color Color2 { get; }"},"M:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory.CreateMultiPlaneFilter(System.Collections.Generic.IList{Autodesk.Revit.DB.Plane})":{"id":"M:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory.CreateMultiPlaneFilter(System.Collections.Generic.IList{Autodesk.Revit.DB.Plane})","title":"PointCloudFilterFactory.CreateMultiPlaneFilter(IList<Plane>) Method","ns":"Autodesk.Revit.DB.PointClouds","sig":"public static PointCloudFilter CreateMultiPlaneFilter(\n\tIList<Plane> planes\n)"},"T:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory":{"id":"T:Autodesk.Revit.DB.PointClouds.PointCloudFilterFactory","title":"PointCloudFilterFactory Class","ns":"Autodesk.Revit.DB.PointClouds","desc":"A factory class for creating point cloud filters.","sig":"public static class PointCloudFilterFactory","inherit":["SystemObject","Autodesk.Revit.DB.PointCloudsPointCloudFilterFactory"],"members":{"methods":[{"n":"CreateMultiPlaneFilter(IListPlane)","d":""},{"n":"CreateMultiPlaneFilter(IListPlane, Int32)","d":""}]}}}